spring:
  application:
    name: tool-service

logging:
  file:
    name: ${LOG_DIR:./logs}/tool-service.log

server:
  port: 1406
  servlet:
    context-path: /tool-service
  compression:
    enabled: true
    min-response-size: 512
