version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USERNAME:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD:-guest}
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2605:2605"
    environment:
      DB_NAME: ${DB_NAME:-kira}
      DB_APP_USER: ${DB_APP_USER:-kira_user}
      DB_APP_PASSWORD: ${DB_APP_PASSWORD:-kira_password}
      DB_PRIMARY_HOST: host.docker.internal
      DB_PRIMARY_PORT: ${DB_PRIMARY_PORT:-3310}
      DB_REPLICA_HOST: host.docker.internal
      DB_REPLICA_PORT: ${DB_REPLICA_PORT:-3311}
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Cho Playwright nếu cần truy cập host
    tty: true  # Giữ container luôn chạy (tốt cho Playwright headless)

volumes:
  mysql_data:
