application:
  datasource:
    write:
      jdbc-url: "jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:kira}?useUnicode=true&createDatabaseIfNotExist=true"
      username: "${DB_USERNAME:root}"
      password: "${DB_PASSWORD:1234}"
      driver-class-name: com.mysql.cj.jdbc.Driver
spring:
  application:
    name: kira-service
  profiles:
    active: composite
  output:
    ansi:
      enabled: NEVER
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  task:
    scheduling:
      pool:
        size: 12
    execution:
      pool:
        core-size: 12
  rabbitmq:
    host: ${DB_HOST:localhost}
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: false
server:
  port: 2308
  servlet:
    context-path: /api
  compression:
    enabled: true
    min-response-size: 512

logging:
  level:
    root: info
  file:
    name: target/kira.log
