drop table if exists events;
create table events
(
    event_id                bigint auto_increment primary key,
    detail_link             text,
    event_name              varchar(255),
    event_date              datetime,
    league_name             varchar(355),
    league_id               int,
    number_updated          int       default 0,
    first_home_odds         float,
    last_home_odds          float,
    first_away_odds         float,
    last_away_odds          float,
    first_over_odds         float,
    last_over_odds          float,
    first_under_odds        float,
    last_under_odds         float,
    first_hdc               varchar(25),
    last_hdc                varchar(25),
    first_ou                varchar(25),
    last_ou                 varchar(25),
    home_logo               text,
    away_logo               text,
    first_corner            varchar(25),
    first_over_corner_odds  float,
    first_under_corner_odds float,
    last_corner             varchar(25),
    last_over_corner_odds   float,
    last_under_corner_odds  float,
    last_update             timestamp default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    index idx_event (event_date, league_name, event_name),
    index idx_event_league (league_id),
    constraint event_unique unique (event_date, event_name)
);
