CREATE TABLE users (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, email VARCHAR(190) NOT NULL, password_hash VARCHAR(255) NOT NULL,
 full_name VARCHAR(150) NOT NULL, phone VARCHAR(30), status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
 created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), created_by BIGINT, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), updated_by BIGINT,
 version BIGINT NOT NULL DEFAULT 0, deleted_at TIMESTAMP(6), CONSTRAINT uk_users_email UNIQUE(email)
);
CREATE TABLE roles (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(40) NOT NULL, CONSTRAINT uk_roles_name UNIQUE(name));
CREATE TABLE user_roles (user_id BIGINT NOT NULL, role_id BIGINT NOT NULL, PRIMARY KEY(user_id,role_id), FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(role_id) REFERENCES roles(id));
CREATE TABLE refresh_tokens (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, token_hash CHAR(64) NOT NULL, family_id CHAR(36) NOT NULL,
 expires_at TIMESTAMP(6) NOT NULL, revoked_at TIMESTAMP(6), replaced_by_hash CHAR(64), created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 created_by BIGINT, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), updated_by BIGINT, version BIGINT NOT NULL DEFAULT 0, deleted_at TIMESTAMP(6),
 CONSTRAINT uk_refresh_hash UNIQUE(token_hash), FOREIGN KEY(user_id) REFERENCES users(id), INDEX idx_refresh_user_family(user_id,family_id)
);
CREATE TABLE password_reset_tokens (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, token_hash CHAR(64) NOT NULL UNIQUE, expires_at TIMESTAMP(6) NOT NULL, used_at TIMESTAMP(6), created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), FOREIGN KEY(user_id) REFERENCES users(id));

CREATE TABLE banks (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, code VARCHAR(30) NOT NULL, name VARCHAR(150) NOT NULL, short_name VARCHAR(80), logo_url VARCHAR(500), website VARCHAR(500), hotline VARCHAR(40), brand_color VARCHAR(20), description TEXT, active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), created_by BIGINT, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), updated_by BIGINT, version BIGINT NOT NULL DEFAULT 0, deleted_at TIMESTAMP(6), UNIQUE(code), INDEX idx_bank_active_name(active,name)
);
CREATE TABLE credit_card_catalogs (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, bank_id BIGINT NOT NULL, card_name VARCHAR(150) NOT NULL, card_code VARCHAR(50) NOT NULL, card_network VARCHAR(30) NOT NULL, card_tier VARCHAR(50), card_type VARCHAR(40), annual_fee DECIMAL(19,4) NOT NULL DEFAULT 0, currency CHAR(3) NOT NULL DEFAULT 'VND', cashback_limit DECIMAL(19,4), default_statement_day TINYINT, default_due_day TINYINT, minimum_payment_rule VARCHAR(500), cashback_condition TEXT, description TEXT, terms_url VARCHAR(500), image_url VARCHAR(500), active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), created_by BIGINT, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), updated_by BIGINT, version BIGINT NOT NULL DEFAULT 0, deleted_at TIMESTAMP(6), UNIQUE(bank_id,card_code), FOREIGN KEY(bank_id) REFERENCES banks(id), INDEX idx_card_catalog_active(active,card_name)
);
CREATE TABLE mccs (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, code CHAR(4) NOT NULL, name VARCHAR(180) NOT NULL, category VARCHAR(100), description TEXT, merchant_type VARCHAR(100), active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), created_by BIGINT, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), updated_by BIGINT, version BIGINT NOT NULL DEFAULT 0, deleted_at TIMESTAMP(6), UNIQUE(code), INDEX idx_mcc_name(name), INDEX idx_mcc_category(category)
);
CREATE TABLE cashback_rules (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, card_catalog_id BIGINT NOT NULL, mcc_id BIGINT, mcc_group VARCHAR(100), cashback_rate DECIMAL(9,6) NOT NULL, cashback_cap DECIMAL(19,4), minimum_spending DECIMAL(19,4), eligible_amount_limit DECIMAL(19,4), limit_cycle VARCHAR(30), effective_from DATE NOT NULL, effective_to DATE, conditions_text TEXT, exclusions_text TEXT, active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), created_by BIGINT, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), updated_by BIGINT, version BIGINT NOT NULL DEFAULT 0, deleted_at TIMESTAMP(6), FOREIGN KEY(card_catalog_id) REFERENCES credit_card_catalogs(id), FOREIGN KEY(mcc_id) REFERENCES mccs(id), INDEX idx_cashback_find(mcc_id,active,effective_from,effective_to)
);
CREATE TABLE user_credit_cards (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, card_catalog_id BIGINT NOT NULL, nickname VARCHAR(100) NOT NULL, last_four CHAR(4), credit_limit DECIMAL(19,4) NOT NULL, currency CHAR(3) NOT NULL DEFAULT 'VND', statement_day TINYINT NOT NULL, due_day TINYINT NOT NULL, opened_date DATE, status VARCHAR(30) NOT NULL, note TEXT,
 created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), created_by BIGINT, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), updated_by BIGINT, version BIGINT NOT NULL DEFAULT 0, deleted_at TIMESTAMP(6), FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(card_catalog_id) REFERENCES credit_card_catalogs(id), INDEX idx_user_cards(user_id,status)
);
CREATE TABLE merchants (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(180) NOT NULL, mcc_id BIGINT, website VARCHAR(500), created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), created_by BIGINT, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), updated_by BIGINT, version BIGINT NOT NULL DEFAULT 0, deleted_at TIMESTAMP(6), FOREIGN KEY(mcc_id) REFERENCES mccs(id), INDEX idx_merchant_name(name));
CREATE TABLE attachments (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, module VARCHAR(40) NOT NULL, document_type VARCHAR(60) NOT NULL, storage_key VARCHAR(500) NOT NULL, original_name VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, size_bytes BIGINT NOT NULL, sha256 CHAR(64) NOT NULL, ai_status VARCHAR(30) NOT NULL DEFAULT 'NOT_REQUESTED', created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), created_by BIGINT, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), updated_by BIGINT, version BIGINT NOT NULL DEFAULT 0, deleted_at TIMESTAMP(6), FOREIGN KEY(user_id) REFERENCES users(id), INDEX idx_attachment_owner(user_id,module));
CREATE TABLE card_transactions (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, user_card_id BIGINT NOT NULL, transaction_date DATETIME(6) NOT NULL, posted_date DATETIME(6), merchant_id BIGINT, mcc_id BIGINT, amount DECIMAL(19,4) NOT NULL, currency CHAR(3) NOT NULL DEFAULT 'VND', original_amount DECIMAL(19,4), original_currency CHAR(3), description VARCHAR(500), reference_number VARCHAR(100), expected_cashback DECIMAL(19,4) NOT NULL DEFAULT 0, status VARCHAR(30) NOT NULL, attachment_id BIGINT, note TEXT,
 created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), created_by BIGINT, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), updated_by BIGINT, version BIGINT NOT NULL DEFAULT 0, deleted_at TIMESTAMP(6), FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(user_card_id) REFERENCES user_credit_cards(id), FOREIGN KEY(merchant_id) REFERENCES merchants(id), FOREIGN KEY(mcc_id) REFERENCES mccs(id), FOREIGN KEY(attachment_id) REFERENCES attachments(id), INDEX idx_tx_owner_date(user_id,transaction_date), UNIQUE(user_id,user_card_id,reference_number)
);
CREATE TABLE statements (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, user_card_id BIGINT NOT NULL, period_start DATE NOT NULL, period_end DATE NOT NULL, statement_date DATE NOT NULL, due_date DATE NOT NULL, opening_balance DECIMAL(19,4) NOT NULL DEFAULT 0, total_spending DECIMAL(19,4) NOT NULL DEFAULT 0, total_refund DECIMAL(19,4) NOT NULL DEFAULT 0, total_fee DECIMAL(19,4) NOT NULL DEFAULT 0, total_interest DECIMAL(19,4) NOT NULL DEFAULT 0, minimum_payment DECIMAL(19,4) NOT NULL DEFAULT 0, statement_balance DECIMAL(19,4) NOT NULL, expected_cashback DECIMAL(19,4) NOT NULL DEFAULT 0, actual_cashback DECIMAL(19,4) NOT NULL DEFAULT 0, paid_amount DECIMAL(19,4) NOT NULL DEFAULT 0, remaining_amount DECIMAL(19,4) NOT NULL, status VARCHAR(30) NOT NULL, attachment_id BIGINT, note TEXT,
 created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), created_by BIGINT, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), updated_by BIGINT, version BIGINT NOT NULL DEFAULT 0, deleted_at TIMESTAMP(6), FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(user_card_id) REFERENCES user_credit_cards(id), FOREIGN KEY(attachment_id) REFERENCES attachments(id), UNIQUE(user_card_id,statement_date), INDEX idx_statement_owner_due(user_id,due_date,status), CHECK(remaining_amount >= 0)
);
CREATE TABLE statement_transactions (statement_id BIGINT NOT NULL, transaction_id BIGINT NOT NULL, PRIMARY KEY(statement_id,transaction_id), UNIQUE(transaction_id), FOREIGN KEY(statement_id) REFERENCES statements(id), FOREIGN KEY(transaction_id) REFERENCES card_transactions(id));
CREATE TABLE payments (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, statement_id BIGINT NOT NULL, payment_date DATETIME(6) NOT NULL, amount DECIMAL(19,4) NOT NULL, payment_method VARCHAR(50), source_account VARCHAR(100), reference_number VARCHAR(100) NOT NULL, status VARCHAR(30) NOT NULL, attachment_id BIGINT, note TEXT, idempotency_key VARCHAR(100) NOT NULL,
 created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), created_by BIGINT, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), updated_by BIGINT, version BIGINT NOT NULL DEFAULT 0, deleted_at TIMESTAMP(6), FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(statement_id) REFERENCES statements(id), FOREIGN KEY(attachment_id) REFERENCES attachments(id), UNIQUE(user_id,idempotency_key), UNIQUE(user_id,reference_number), CHECK(amount > 0)
);
CREATE TABLE cashback_records (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, transaction_id BIGINT, user_card_id BIGINT NOT NULL, bank_id BIGINT NOT NULL, mcc_id BIGINT, eligible_amount DECIMAL(19,4) NOT NULL, cashback_rate DECIMAL(9,6) NOT NULL, expected_cashback DECIMAL(19,4) NOT NULL, actual_cashback DECIMAL(19,4) NOT NULL DEFAULT 0, expected_receive_date DATE, actual_receive_date DATE, statement_id BIGINT, status VARCHAR(30) NOT NULL, reason VARCHAR(500), note TEXT,
 created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), created_by BIGINT, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), updated_by BIGINT, version BIGINT NOT NULL DEFAULT 0, deleted_at TIMESTAMP(6), FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(transaction_id) REFERENCES card_transactions(id), FOREIGN KEY(user_card_id) REFERENCES user_credit_cards(id), FOREIGN KEY(bank_id) REFERENCES banks(id), FOREIGN KEY(mcc_id) REFERENCES mccs(id), FOREIGN KEY(statement_id) REFERENCES statements(id), UNIQUE(transaction_id)
);
CREATE TABLE service_providers (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(150) NOT NULL UNIQUE, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), created_by BIGINT, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), updated_by BIGINT, version BIGINT NOT NULL DEFAULT 0, deleted_at TIMESTAMP(6));
CREATE TABLE discount_invoices (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, user_card_id BIGINT NOT NULL, merchant_id BIGINT, service_provider_id BIGINT NOT NULL, invoice_number VARCHAR(100) NOT NULL, invoice_date DATE NOT NULL, invoice_amount DECIMAL(19,4) NOT NULL, amount_paid DECIMAL(19,4) NOT NULL, service_discount_rate DECIMAL(9,6) NOT NULL DEFAULT 0, service_discount_amount DECIMAL(19,4) NOT NULL DEFAULT 0, additional_fee DECIMAL(19,4) NOT NULL DEFAULT 0, cashback_rate DECIMAL(9,6) NOT NULL DEFAULT 0, expected_cashback DECIMAL(19,4) NOT NULL DEFAULT 0, actual_cashback DECIMAL(19,4) NOT NULL DEFAULT 0, expected_receive_date DATE, actual_receive_date DATE, expected_profit DECIMAL(19,4) NOT NULL DEFAULT 0, actual_profit DECIMAL(19,4) NOT NULL DEFAULT 0, capital_locked DECIMAL(19,4) NOT NULL DEFAULT 0, status VARCHAR(40) NOT NULL, attachment_id BIGINT, note TEXT,
 created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), created_by BIGINT, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), updated_by BIGINT, version BIGINT NOT NULL DEFAULT 0, deleted_at TIMESTAMP(6), FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(user_card_id) REFERENCES user_credit_cards(id), FOREIGN KEY(merchant_id) REFERENCES merchants(id), FOREIGN KEY(service_provider_id) REFERENCES service_providers(id), FOREIGN KEY(attachment_id) REFERENCES attachments(id), UNIQUE(user_id,invoice_number)
);

CREATE TABLE investment_platforms (id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(150) NOT NULL, code VARCHAR(50) NOT NULL UNIQUE, website_url VARCHAR(500), logo_url VARCHAR(500), description TEXT, active BOOLEAN NOT NULL DEFAULT TRUE, note TEXT, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), created_by BIGINT, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), updated_by BIGINT, version BIGINT NOT NULL DEFAULT 0, deleted_at TIMESTAMP(6));
CREATE TABLE investment_accounts (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, platform_id BIGINT NOT NULL, account_name VARCHAR(150) NOT NULL, external_account_code VARCHAR(100), currency CHAR(3) NOT NULL DEFAULT 'VND', current_balance DECIMAL(19,4) NOT NULL DEFAULT 0, available_capital DECIMAL(19,4) NOT NULL DEFAULT 0, locked_capital DECIMAL(19,4) NOT NULL DEFAULT 0, accumulated_profit DECIMAL(19,4) NOT NULL DEFAULT 0, accumulated_reward DECIMAL(19,4) NOT NULL DEFAULT 0, reserved_withdrawal DECIMAL(19,4) NOT NULL DEFAULT 0, status VARCHAR(30) NOT NULL, note TEXT,
 created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), created_by BIGINT, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), updated_by BIGINT, version BIGINT NOT NULL DEFAULT 0, deleted_at TIMESTAMP(6), FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(platform_id) REFERENCES investment_platforms(id), UNIQUE(user_id,platform_id,external_account_code), INDEX idx_invest_account_owner(user_id,status), CHECK(available_capital >= 0), CHECK(locked_capital >= 0), CHECK(reserved_withdrawal >= 0)
);
CREATE TABLE investment_deposits (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, investment_account_id BIGINT NOT NULL, deposit_date DATETIME(6) NOT NULL, amount DECIMAL(19,4) NOT NULL, fee DECIMAL(19,4) NOT NULL DEFAULT 0, net_received_amount DECIMAL(19,4) NOT NULL, payment_method VARCHAR(50), reference_number VARCHAR(100) NOT NULL, status VARCHAR(30) NOT NULL, attachment_id BIGINT, note TEXT, idempotency_key VARCHAR(100) NOT NULL,
 created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), created_by BIGINT, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), updated_by BIGINT, version BIGINT NOT NULL DEFAULT 0, deleted_at TIMESTAMP(6), FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(investment_account_id) REFERENCES investment_accounts(id), FOREIGN KEY(attachment_id) REFERENCES attachments(id), UNIQUE(user_id,idempotency_key), UNIQUE(investment_account_id,reference_number), CHECK(amount > 0), CHECK(fee >= 0)
);
CREATE TABLE investment_tasks (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, investment_account_id BIGINT NOT NULL, task_code VARCHAR(100) NOT NULL, task_name VARCHAR(180) NOT NULL, task_type VARCHAR(60), start_date DATETIME(6), expected_completion_date DATETIME(6), actual_completion_date DATETIME(6), allocated_capital DECIMAL(19,4) NOT NULL DEFAULT 0, expected_capital_return DECIMAL(19,4) NOT NULL DEFAULT 0, expected_profit DECIMAL(19,4) NOT NULL DEFAULT 0, expected_reward DECIMAL(19,4) NOT NULL DEFAULT 0, actual_capital_return DECIMAL(19,4) NOT NULL DEFAULT 0, actual_profit DECIMAL(19,4) NOT NULL DEFAULT 0, actual_reward DECIMAL(19,4) NOT NULL DEFAULT 0, status VARCHAR(40) NOT NULL, description TEXT, attachment_id BIGINT, note TEXT, idempotency_key VARCHAR(100),
 created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), created_by BIGINT, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), updated_by BIGINT, version BIGINT NOT NULL DEFAULT 0, deleted_at TIMESTAMP(6), FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(investment_account_id) REFERENCES investment_accounts(id), FOREIGN KEY(attachment_id) REFERENCES attachments(id), UNIQUE(investment_account_id,task_code), UNIQUE(user_id,idempotency_key)
);
CREATE TABLE investment_task_settlements (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, investment_task_id BIGINT NOT NULL, settlement_date DATETIME(6) NOT NULL, total_received DECIMAL(19,4) NOT NULL, capital_returned DECIMAL(19,4) NOT NULL, profit_received DECIMAL(19,4) NOT NULL, reward_received DECIMAL(19,4) NOT NULL, fee DECIMAL(19,4) NOT NULL DEFAULT 0, net_received DECIMAL(19,4) NOT NULL, reference_number VARCHAR(100) NOT NULL, status VARCHAR(30) NOT NULL, attachment_id BIGINT, note TEXT, idempotency_key VARCHAR(100) NOT NULL,
 created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), created_by BIGINT, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), updated_by BIGINT, version BIGINT NOT NULL DEFAULT 0, deleted_at TIMESTAMP(6), FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(investment_task_id) REFERENCES investment_tasks(id), FOREIGN KEY(attachment_id) REFERENCES attachments(id), UNIQUE(investment_task_id), UNIQUE(user_id,idempotency_key)
);
CREATE TABLE investment_rewards (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, investment_account_id BIGINT NOT NULL, investment_task_id BIGINT, reward_type VARCHAR(40) NOT NULL, reward_source VARCHAR(150), reward_date DATETIME(6) NOT NULL, amount DECIMAL(19,4) NOT NULL, status VARCHAR(30) NOT NULL, condition_description TEXT, attachment_id BIGINT, note TEXT, idempotency_key VARCHAR(100) NOT NULL,
 created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), created_by BIGINT, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), updated_by BIGINT, version BIGINT NOT NULL DEFAULT 0, deleted_at TIMESTAMP(6), FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(investment_account_id) REFERENCES investment_accounts(id), FOREIGN KEY(investment_task_id) REFERENCES investment_tasks(id), FOREIGN KEY(attachment_id) REFERENCES attachments(id), UNIQUE(user_id,idempotency_key)
);
CREATE TABLE investment_withdrawals (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, investment_account_id BIGINT NOT NULL, requested_date DATETIME(6) NOT NULL, requested_amount DECIMAL(19,4) NOT NULL, withdrawal_fee DECIMAL(19,4) NOT NULL DEFAULT 0, expected_net_amount DECIMAL(19,4) NOT NULL, actual_net_amount DECIMAL(19,4), destination_account VARCHAR(180), reference_number VARCHAR(100) NOT NULL, expected_receive_date DATE, actual_receive_date DATE, status VARCHAR(40) NOT NULL, attachment_id BIGINT, note TEXT, idempotency_key VARCHAR(100) NOT NULL,
 created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), created_by BIGINT, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), updated_by BIGINT, version BIGINT NOT NULL DEFAULT 0, deleted_at TIMESTAMP(6), FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(investment_account_id) REFERENCES investment_accounts(id), FOREIGN KEY(attachment_id) REFERENCES attachments(id), UNIQUE(user_id,idempotency_key), UNIQUE(investment_account_id,reference_number), CHECK(requested_amount > 0)
);
CREATE TABLE investment_ledger_entries (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, investment_account_id BIGINT NOT NULL, entry_date DATETIME(6) NOT NULL, entry_type VARCHAR(40) NOT NULL, amount DECIMAL(19,4) NOT NULL, currency CHAR(3) NOT NULL DEFAULT 'VND', balance_before DECIMAL(19,4) NOT NULL, balance_after DECIMAL(19,4) NOT NULL, reference_type VARCHAR(50) NOT NULL, reference_id BIGINT NOT NULL, description VARCHAR(500), idempotency_key VARCHAR(100) NOT NULL,
 created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), created_by BIGINT, UNIQUE(investment_account_id,idempotency_key), FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(investment_account_id) REFERENCES investment_accounts(id), INDEX idx_ledger_account_date(investment_account_id,entry_date), CHECK(balance_after >= 0)
);
CREATE TABLE notifications (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, type VARCHAR(50) NOT NULL, module VARCHAR(40) NOT NULL, title VARCHAR(180) NOT NULL, message TEXT NOT NULL, severity VARCHAR(20) NOT NULL, read_at TIMESTAMP(6), deep_link VARCHAR(500), created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), created_by BIGINT, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), updated_by BIGINT, version BIGINT NOT NULL DEFAULT 0, deleted_at TIMESTAMP(6), FOREIGN KEY(user_id) REFERENCES users(id), INDEX idx_notification_user_read(user_id,read_at,created_at));
CREATE TABLE audit_logs (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT, action VARCHAR(80) NOT NULL, entity_type VARCHAR(80), entity_id VARCHAR(100), before_data JSON, after_data JSON, ip_address VARCHAR(45), user_agent VARCHAR(500), trace_id VARCHAR(64), created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX idx_audit_entity(entity_type,entity_id), INDEX idx_audit_user_date(user_id,created_at));
CREATE TABLE application_settings (id BIGINT PRIMARY KEY AUTO_INCREMENT, setting_key VARCHAR(100) NOT NULL UNIQUE, setting_value TEXT, description VARCHAR(500), encrypted BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), created_by BIGINT, updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), updated_by BIGINT, version BIGINT NOT NULL DEFAULT 0, deleted_at TIMESTAMP(6));

