CREATE TABLE card_statement_imports
(
  id                    BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id               BIGINT       NOT NULL,
  user_card_id          BIGINT       NOT NULL,
  status                VARCHAR(30)  NOT NULL,
  attempt_count         INT          NOT NULL DEFAULT 0,
  next_attempt_at       TIMESTAMP(6),
  processing_started_at TIMESTAMP(6),
  ai_model              VARCHAR(150),
  ai_result             JSON,
  ai_error              VARCHAR(100),
  statement_id          BIGINT,
  confirm_result        JSON,
  completed_at          TIMESTAMP(6),
  retention_until       TIMESTAMP(6),
  storage_purged_at     TIMESTAMP(6),
  created_at            TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by            BIGINT,
  updated_at            TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  updated_by            BIGINT,
  version               BIGINT       NOT NULL DEFAULT 0,
  deleted_at            TIMESTAMP(6),
  CONSTRAINT fk_card_import_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_card_import_card FOREIGN KEY (user_card_id) REFERENCES user_credit_cards (id),
  CONSTRAINT fk_card_import_statement FOREIGN KEY (statement_id) REFERENCES statements (id),
  INDEX idx_card_import_claim (status, next_attempt_at),
  INDEX idx_card_import_owner_created (user_id, created_at),
  INDEX idx_card_import_card_created (user_card_id, created_at),
  INDEX idx_card_import_retention (status, retention_until),
  CONSTRAINT chk_card_import_status CHECK (status IN
    ('QUEUED', 'PROCESSING', 'READY', 'FAILED', 'CONFIRMED', 'CANCELLED'))
);

CREATE TABLE card_statement_import_files
(
  id            BIGINT PRIMARY KEY AUTO_INCREMENT,
  import_id     BIGINT       NOT NULL,
  attachment_id BIGINT       NOT NULL,
  page_number   INT          NOT NULL,
  created_at    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by    BIGINT,
  updated_at    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  updated_by    BIGINT,
  version       BIGINT       NOT NULL DEFAULT 0,
  deleted_at    TIMESTAMP(6),
  CONSTRAINT fk_card_import_file_import FOREIGN KEY (import_id) REFERENCES card_statement_imports (id),
  CONSTRAINT fk_card_import_file_attachment FOREIGN KEY (attachment_id) REFERENCES attachments (id),
  CONSTRAINT uq_card_import_file UNIQUE (import_id, attachment_id),
  INDEX idx_card_import_file_attachment (attachment_id)
);

CREATE TABLE card_transactions
(
  id               BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id          BIGINT         NOT NULL,
  user_card_id     BIGINT         NOT NULL,
  statement_id     BIGINT,
  import_id        BIGINT,
  transaction_date DATE           NOT NULL,
  posting_date     DATE,
  description      VARCHAR(500)   NOT NULL,
  amount           DECIMAL(19, 4) NOT NULL,
  currency         CHAR(3)        NOT NULL,
  transaction_type VARCHAR(20)    NOT NULL,
  mcc_code         CHAR(4),
  cashback_rule_id BIGINT,
  source           VARCHAR(20)    NOT NULL,
  dedup_key        BINARY(32)     NOT NULL,
  created_at       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by       BIGINT,
  updated_at       TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  updated_by       BIGINT,
  version          BIGINT         NOT NULL DEFAULT 0,
  deleted_at       TIMESTAMP(6),
  CONSTRAINT fk_card_tx_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_card_tx_card FOREIGN KEY (user_card_id) REFERENCES user_credit_cards (id),
  CONSTRAINT fk_card_tx_statement FOREIGN KEY (statement_id) REFERENCES statements (id),
  CONSTRAINT fk_card_tx_import FOREIGN KEY (import_id) REFERENCES card_statement_imports (id),
  CONSTRAINT fk_card_tx_rule FOREIGN KEY (cashback_rule_id) REFERENCES credit_card_cashback_rules (id),
  CONSTRAINT uq_card_tx_dedup UNIQUE (user_card_id, dedup_key),
  INDEX idx_card_tx_card_date (user_card_id, transaction_date),
  INDEX idx_card_tx_statement (statement_id),
  CONSTRAINT chk_card_tx_amount CHECK (amount > 0),
  CONSTRAINT chk_card_tx_type CHECK (transaction_type IN ('SPENDING', 'REFUND', 'FEE', 'INTEREST', 'CASHBACK')),
  CONSTRAINT chk_card_tx_source CHECK (source IN ('AI_IMPORT', 'MANUAL'))
);
