use kira;

alter table leagues
    add column if not exists country_code_short char(3) null after country;

set @league_country_code_short_idx := (
    select if(
        count(*) = 0,
        'alter table leagues add index idx_country_code_short (country_code_short)',
        'select 1'
    )
    from information_schema.statistics
    where table_schema = database()
      and table_name = 'leagues'
      and index_name = 'idx_country_code_short'
);
prepare league_country_code_short_idx_stmt from @league_country_code_short_idx;
execute league_country_code_short_idx_stmt;
deallocate prepare league_country_code_short_idx_stmt;

create temporary table if not exists league_country_code_short_map
(
    country_name varchar(255) primary key,
    country_code_short char(3) not null
);

truncate table league_country_code_short_map;

insert into league_country_code_short_map (country_name, country_code_short)
values
    ('a rap xe ut', 'KSA'),
    ('abw', 'ARU'),
    ('ad', 'AND'),
    ('ae', 'UAE'),
    ('af', 'AFG'),
    ('afg', 'AFG'),
    ('afghanistan', 'AFG'),
    ('ag', 'ATG'),
    ('ago', 'ANG'),
    ('aho', 'ANT'),
    ('ai', 'AIA'),
    ('aia', 'AIA'),
    ('al', 'ALB'),
    ('ala', 'ALD'),
    ('aland islands', 'ALD'),
    ('alb', 'ALB'),
    ('albania', 'ALB'),
    ('ald', 'ALD'),
    ('alg', 'ALG'),
    ('algeria', 'ALG'),
    ('am', 'ARM'),
    ('american samoa', 'ASA'),
    ('an do', 'IND'),
    ('and', 'AND'),
    ('andorra', 'AND'),
    ('ang', 'ANG'),
    ('angola', 'ANG'),
    ('anguilla', 'AIA'),
    ('ant', 'ANT'),
    ('antigua and barbuda', 'ATG'),
    ('ao', 'ANG'),
    ('ar', 'ARG'),
    ('arab republic of egypt', 'EGY'),
    ('are', 'UAE'),
    ('arg', 'ARG'),
    ('argentina', 'ARG'),
    ('argentine republic', 'ARG'),
    ('arm', 'ARM'),
    ('armenia', 'ARM'),
    ('aru', 'ARU'),
    ('aruba', 'ARU'),
    ('as', 'ASA'),
    ('asa', 'ASA'),
    ('asm', 'ASA'),
    ('at', 'AUT'),
    ('atg', 'ATG'),
    ('au', 'AUS'),
    ('aus', 'AUS'),
    ('australia', 'AUS'),
    ('austria', 'AUT'),
    ('aut', 'AUT'),
    ('aw', 'ARU'),
    ('ax', 'ALD'),
    ('az', 'AZE'),
    ('aze', 'AZE'),
    ('azerbaijan', 'AZE'),
    ('ba', 'BIH'),
    ('bah', 'BAH'),
    ('bahamas', 'BAH'),
    ('bahamas the', 'BAH'),
    ('bahrain', 'BHR'),
    ('ban', 'BAN'),
    ('bangladesh', 'BAN'),
    ('bar', 'BRB'),
    ('barbados', 'BRB'),
    ('bb', 'BRB'),
    ('bd', 'BAN'),
    ('bdi', 'BDI'),
    ('be', 'BEL'),
    ('bel', 'BEL'),
    ('belarus', 'BLR'),
    ('belgium', 'BEL'),
    ('belize', 'BLZ'),
    ('ben', 'BEN'),
    ('benin', 'BEN'),
    ('ber', 'BER'),
    ('bermuda', 'BER'),
    ('bes', 'ANT'),
    ('bf', 'BFA'),
    ('bfa', 'BFA'),
    ('bg', 'BUL'),
    ('bgd', 'BAN'),
    ('bgr', 'BUL'),
    ('bh', 'BHR'),
    ('bhr', 'BHR'),
    ('bhs', 'BAH'),
    ('bhu', 'BHU'),
    ('bhutan', 'BHU'),
    ('bi', 'BDI'),
    ('bih', 'BIH'),
    ('biz', 'BLZ'),
    ('bj', 'BEN'),
    ('blr', 'BLR'),
    ('blz', 'BLZ'),
    ('bm', 'BER'),
    ('bmu', 'BER'),
    ('bn', 'BRU'),
    ('bo', 'BOL'),
    ('bol', 'BOL'),
    ('bolivarian republic of venezuela', 'VEN'),
    ('bolivia', 'BOL'),
    ('bolivia plurinational state of', 'BOL'),
    ('bonaire sint eustatius and saba', 'ANT'),
    ('bosnia', 'BIH'),
    ('bosnia and herzegovina', 'BIH'),
    ('bot', 'BOT'),
    ('botswana', 'BOT'),
    ('bq', 'ANT'),
    ('br', 'BRA'),
    ('bra', 'BRA'),
    ('brazil', 'BRA'),
    ('brb', 'BRB'),
    ('britain', 'ENG'),
    ('british virgin islands', 'VGB'),
    ('brn', 'BRU'),
    ('bru', 'BRU'),
    ('brunei', 'BRU'),
    ('brunei darussalam', 'BRU'),
    ('bs', 'BAH'),
    ('bt', 'BHU'),
    ('btn', 'BHU'),
    ('bul', 'BUL'),
    ('bulgaria', 'BUL'),
    ('bur', 'BFA'),
    ('burkina faso', 'BFA'),
    ('burundi', 'BDI'),
    ('bw', 'BOT'),
    ('bwa', 'BOT'),
    ('by', 'BLR'),
    ('bz', 'BLZ'),
    ('ca', 'CAN'),
    ('cabo verde', 'CPV'),
    ('caf', 'CTA'),
    ('cam', 'CAM'),
    ('cambodia', 'CAM'),
    ('cameroon', 'CMR'),
    ('can', 'CAN'),
    ('canada', 'CAN'),
    ('cape verde', 'CPV'),
    ('caribbean netherlands', 'ANT'),
    ('cay', 'CAY'),
    ('cayman islands', 'CAY'),
    ('cc', 'CCK'),
    ('cck', 'CCK'),
    ('cd', 'COD'),
    ('central african republic', 'CTA'),
    ('central african republic the', 'CTA'),
    ('cf', 'CTA'),
    ('cg', 'CGO'),
    ('cgo', 'CGO'),
    ('ch', 'SUI'),
    ('cha', 'CHA'),
    ('chad', 'CHA'),
    ('che', 'SUI'),
    ('chi', 'CHI'),
    ('chile', 'CHI'),
    ('china', 'CHN'),
    ('china hong kong special administrative region', 'HKG'),
    ('china macao special administrative region', 'MAC'),
    ('chl', 'CHI'),
    ('chn', 'CHN'),
    ('christmas island', 'CXR'),
    ('ci', 'CIV'),
    ('civ', 'CIV'),
    ('ck', 'COK'),
    ('cl', 'CHI'),
    ('cm', 'CMR'),
    ('cmr', 'CMR'),
    ('cn', 'CHN'),
    ('co', 'COL'),
    ('co operative republic of guyana', 'GUY'),
    ('cocos islands', 'CCK'),
    ('cocos keeling islands', 'CCK'),
    ('cod', 'COD'),
    ('cog', 'CGO'),
    ('cok', 'COK'),
    ('col', 'COL'),
    ('colombia', 'COL'),
    ('com', 'COM'),
    ('commonwealth of dominica', 'DMA'),
    ('commonwealth of the bahamas', 'BAH'),
    ('comoros', 'COM'),
    ('comoros the', 'COM'),
    ('congo', 'COD'),
    ('congo brazzaville', 'CGO'),
    ('congo kinshasa', 'COD'),
    ('congo the', 'CGO'),
    ('congo the democratic republic of the', 'COD'),
    ('cook islands', 'COK'),
    ('cook islands the', 'COK'),
    ('costa rica', 'CRC'),
    ('cote divoire', 'CIV'),
    ('cpv', 'CPV'),
    ('cr', 'CRC'),
    ('crc', 'CRC'),
    ('cri', 'CRC'),
    ('cro', 'CRO'),
    ('croatia', 'CRO'),
    ('cta', 'CTA'),
    ('cu', 'CUB'),
    ('cub', 'CUB'),
    ('cuba', 'CUB'),
    ('curacao', 'CUW'),
    ('cuw', 'CUW'),
    ('cv', 'CPV'),
    ('cw', 'CUW'),
    ('cx', 'CXR'),
    ('cxr', 'CXR'),
    ('cy', 'CYP'),
    ('cym', 'CAY'),
    ('cyp', 'CYP'),
    ('cyprus', 'CYP'),
    ('cz', 'CZE'),
    ('cze', 'CZE'),
    ('czech', 'CZE'),
    ('czech republic', 'CZE'),
    ('czechia', 'CZE'),
    ('de', 'GER'),
    ('democratic peoples republic of korea', 'PRK'),
    ('democratic peoples republic of korea the', 'PRK'),
    ('democratic republic of sao tome and principe', 'STP'),
    ('democratic republic of the congo', 'COD'),
    ('democratic republic of the congo the', 'COD'),
    ('democratic republic of timor leste', 'TLS'),
    ('democratic socialist republic of sri lanka', 'SRI'),
    ('den', 'DEN'),
    ('denmark', 'DEN'),
    ('deu', 'GER'),
    ('dj', 'DJI'),
    ('dji', 'DJI'),
    ('djibouti', 'DJI'),
    ('dk', 'DEN'),
    ('dm', 'DMA'),
    ('dma', 'DMA'),
    ('dnk', 'DEN'),
    ('do', 'DOM'),
    ('dom', 'DOM'),
    ('dominica', 'DMA'),
    ('dominican republic', 'DOM'),
    ('dominican republic the', 'DOM'),
    ('duc', 'GER'),
    ('dz', 'ALG'),
    ('dza', 'ALG'),
    ('eastern republic of uruguay', 'URU'),
    ('ec', 'ECU'),
    ('ecu', 'ECU'),
    ('ecuador', 'ECU'),
    ('ee', 'EST'),
    ('eg', 'EGY'),
    ('egy', 'EGY'),
    ('egypt', 'EGY'),
    ('eh', 'SAH'),
    ('el salvador', 'SLV'),
    ('emirates', 'UAE'),
    ('eng', 'ENG'),
    ('england', 'ENG'),
    ('eqg', 'EQG'),
    ('equatorial guinea', 'EQG'),
    ('er', 'ERI'),
    ('eri', 'ERI'),
    ('eritrea', 'ERI'),
    ('es', 'ESP'),
    ('esa', 'SLV'),
    ('esh', 'SAH'),
    ('esp', 'ESP'),
    ('est', 'EST'),
    ('estonia', 'EST'),
    ('eswatini', 'SWZ'),
    ('et', 'ETH'),
    ('eth', 'ETH'),
    ('ethiopia', 'ETH'),
    ('falkland islands', 'FLK'),
    ('falkland islands malvinas', 'FLK'),
    ('far', 'FRO'),
    ('faroe islands', 'FRO'),
    ('federal democratic republic of ethiopia', 'ETH'),
    ('federal republic of germany', 'GER'),
    ('federal republic of nigeria', 'NGA'),
    ('federal republic of somalia', 'SOM'),
    ('federated states of micronesia', 'FSM'),
    ('federative republic of brazil', 'BRA'),
    ('fgu', 'GUF'),
    ('fi', 'FIN'),
    ('fij', 'FIJ'),
    ('fiji', 'FIJ'),
    ('fin', 'FIN'),
    ('finland', 'FIN'),
    ('fj', 'FIJ'),
    ('fji', 'FIJ'),
    ('fk', 'FLK'),
    ('flk', 'FLK'),
    ('fm', 'FSM'),
    ('fo', 'FRO'),
    ('fr', 'FRA'),
    ('fra', 'FRA'),
    ('france', 'FRA'),
    ('french guiana', 'GUF'),
    ('french republic', 'FRA'),
    ('fro', 'FRO'),
    ('fsm', 'FSM'),
    ('ga', 'GAB'),
    ('gab', 'GAB'),
    ('gabon', 'GAB'),
    ('gabonese republic', 'GAB'),
    ('gam', 'GAM'),
    ('gambia', 'GAM'),
    ('gambia the', 'GAM'),
    ('gbg', 'GBG'),
    ('gbj', 'GBJ'),
    ('gbm', 'GBM'),
    ('gbs', 'GNB'),
    ('gd', 'GRN'),
    ('ge', 'GEO'),
    ('geo', 'GEO'),
    ('georgia', 'GEO'),
    ('geq', 'EQG'),
    ('ger', 'GER'),
    ('germany', 'GER'),
    ('gf', 'GUF'),
    ('gg', 'GBG'),
    ('ggy', 'GBG'),
    ('gh', 'GHA'),
    ('gha', 'GHA'),
    ('ghana', 'GHA'),
    ('gi', 'GIB'),
    ('gib', 'GIB'),
    ('gibraltar', 'GIB'),
    ('gin', 'GUI'),
    ('gl', 'GRL'),
    ('glp', 'GLP'),
    ('gm', 'GAM'),
    ('gmb', 'GAM'),
    ('gn', 'GUI'),
    ('gnb', 'GNB'),
    ('gnq', 'EQG'),
    ('gp', 'GLP'),
    ('gq', 'EQG'),
    ('gr', 'GRE'),
    ('grand duchy of luxembourg', 'LUX'),
    ('grc', 'GRE'),
    ('grd', 'GRN'),
    ('gre', 'GRE'),
    ('great britain', 'ENG'),
    ('greece', 'GRE'),
    ('greenland', 'GRL'),
    ('grenada', 'GRN'),
    ('grl', 'GRL'),
    ('grn', 'GRN'),
    ('gt', 'GUA'),
    ('gtm', 'GUA'),
    ('gu', 'GUM'),
    ('gua', 'GUA'),
    ('guadeloupe', 'GLP'),
    ('guam', 'GUM'),
    ('guatemala', 'GUA'),
    ('gud', 'GLP'),
    ('guernsey', 'GBG'),
    ('guf', 'GUF'),
    ('gui', 'GUI'),
    ('guinea', 'GUI'),
    ('guinea bissau', 'GNB'),
    ('gum', 'GUM'),
    ('guy', 'GUY'),
    ('guyana', 'GUY'),
    ('gw', 'GNB'),
    ('gy', 'GUY'),
    ('ha lan', 'NED'),
    ('hai', 'HAI'),
    ('haiti', 'HAI'),
    ('han quoc', 'KOR'),
    ('hashemite kingdom of jordan', 'JOR'),
    ('hel', 'SHN'),
    ('hellenic republic', 'GRE'),
    ('hk', 'HKG'),
    ('hkg', 'HKG'),
    ('hn', 'HON'),
    ('hnd', 'HON'),
    ('holy see', 'VAT'),
    ('holy see the', 'VAT'),
    ('hon', 'HON'),
    ('honduras', 'HON'),
    ('hong kong', 'HKG'),
    ('hr', 'CRO'),
    ('hrv', 'CRO'),
    ('ht', 'HAI'),
    ('hti', 'HAI'),
    ('hu', 'HUN'),
    ('hun', 'HUN'),
    ('hungary', 'HUN'),
    ('iceland', 'ISL'),
    ('id', 'IDN'),
    ('idn', 'IDN'),
    ('ie', 'IRL'),
    ('il', 'ISR'),
    ('im', 'GBM'),
    ('imn', 'GBM'),
    ('in', 'IND'),
    ('ina', 'IDN'),
    ('ind', 'IND'),
    ('independent state of papua new guinea', 'PNG'),
    ('independent state of samoa', 'SAM'),
    ('india', 'IND'),
    ('indonesia', 'IDN'),
    ('iq', 'IRQ'),
    ('ir', 'IRN'),
    ('iran', 'IRN'),
    ('iran islamic republic of', 'IRN'),
    ('iraq', 'IRQ'),
    ('ireland', 'IRL'),
    ('iri', 'IRN'),
    ('irl', 'IRL'),
    ('irn', 'IRN'),
    ('irq', 'IRQ'),
    ('is', 'ISL'),
    ('isl', 'ISL'),
    ('islamic republic of afghanistan', 'AFG'),
    ('islamic republic of iran', 'IRN'),
    ('islamic republic of mauritania', 'MTN'),
    ('islamic republic of pakistan', 'PAK'),
    ('isle of man', 'GBM'),
    ('isr', 'ISR'),
    ('israel', 'ISR'),
    ('isv', 'VIR'),
    ('it', 'ITA'),
    ('ita', 'ITA'),
    ('italy', 'ITA'),
    ('ivb', 'VGB'),
    ('ivory coast', 'CIV'),
    ('jam', 'JAM'),
    ('jamaica', 'JAM'),
    ('japan', 'JPN'),
    ('je', 'GBJ'),
    ('jersey', 'GBJ'),
    ('jey', 'GBJ'),
    ('jm', 'JAM'),
    ('jo', 'JOR'),
    ('jor', 'JOR'),
    ('jordan', 'JOR'),
    ('jp', 'JPN'),
    ('jpn', 'JPN'),
    ('kaz', 'KAZ'),
    ('kazakhstan', 'KAZ'),
    ('ke', 'KEN'),
    ('ken', 'KEN'),
    ('kenya', 'KEN'),
    ('kg', 'KGZ'),
    ('kgz', 'KGZ'),
    ('kh', 'CAM'),
    ('khm', 'CAM'),
    ('ki', 'KIR'),
    ('kingdom of bahrain', 'BHR'),
    ('kingdom of belgium', 'BEL'),
    ('kingdom of bhutan', 'BHU'),
    ('kingdom of cambodia', 'CAM'),
    ('kingdom of denmark', 'DEN'),
    ('kingdom of eswatini', 'SWZ'),
    ('kingdom of lesotho', 'LES'),
    ('kingdom of morocco', 'MAR'),
    ('kingdom of norway', 'NOR'),
    ('kingdom of saudi arabia', 'KSA'),
    ('kingdom of spain', 'ESP'),
    ('kingdom of sweden', 'SWE'),
    ('kingdom of thailand', 'THA'),
    ('kingdom of the netherlands', 'NED'),
    ('kingdom of tonga', 'TGA'),
    ('kir', 'KIR'),
    ('kiribati', 'KIR'),
    ('km', 'COM'),
    ('kn', 'SKN'),
    ('kna', 'SKN'),
    ('kor', 'KOR'),
    ('korea', 'KOR'),
    ('korea republic', 'KOR'),
    ('korea the democratic peoples republic of', 'PRK'),
    ('korea the republic of', 'KOR'),
    ('kosovo', 'KVX'),
    ('kp', 'PRK'),
    ('kr', 'KOR'),
    ('ksa', 'KSA'),
    ('kuw', 'KUW'),
    ('kuwait', 'KUW'),
    ('kw', 'KUW'),
    ('kwt', 'KUW'),
    ('ky', 'CAY'),
    ('kyrgyz republic', 'KGZ'),
    ('kyrgyzstan', 'KGZ'),
    ('kz', 'KAZ'),
    ('la', 'LAO'),
    ('lao', 'LAO'),
    ('lao peoples democratic republic', 'LAO'),
    ('lao peoples democratic republic the', 'LAO'),
    ('laos', 'LAO'),
    ('lat', 'LVA'),
    ('latvia', 'LVA'),
    ('lb', 'LBN'),
    ('lba', 'LBY'),
    ('lbn', 'LBN'),
    ('lbr', 'LBR'),
    ('lby', 'LBY'),
    ('lc', 'LCA'),
    ('lca', 'LCA'),
    ('lebanese republic', 'LBN'),
    ('lebanon', 'LBN'),
    ('les', 'LES'),
    ('lesotho', 'LES'),
    ('li', 'LIE'),
    ('lib', 'LBN'),
    ('liberia', 'LBR'),
    ('libya', 'LBY'),
    ('lie', 'LIE'),
    ('liechtenstein', 'LIE'),
    ('lithuania', 'LTU'),
    ('lk', 'SRI'),
    ('lka', 'SRI'),
    ('lr', 'LBR'),
    ('ls', 'LES'),
    ('lso', 'LES'),
    ('lt', 'LTU'),
    ('ltu', 'LTU'),
    ('lu', 'LUX'),
    ('lux', 'LUX'),
    ('luxembourg', 'LUX'),
    ('lv', 'LVA'),
    ('lva', 'LVA'),
    ('ly', 'LBY'),
    ('ma', 'MAR'),
    ('mac', 'MAC'),
    ('macao', 'MAC'),
    ('mad', 'MAD'),
    ('madagascar', 'MAD'),
    ('malawi', 'MWI'),
    ('malaysia', 'MAS'),
    ('maldives', 'MDV'),
    ('mali', 'MLI'),
    ('malta', 'MLT'),
    ('mar', 'MAR'),
    ('marshall islands', 'MHL'),
    ('marshall islands the', 'MHL'),
    ('martinique', 'MTQ'),
    ('mas', 'MAS'),
    ('mauritania', 'MTN'),
    ('mauritius', 'MRI'),
    ('maw', 'MWI'),
    ('may', 'MYT'),
    ('mayotte', 'MYT'),
    ('mc', 'MON'),
    ('mco', 'MON'),
    ('md', 'MDA'),
    ('mda', 'MDA'),
    ('mdg', 'MAD'),
    ('mdv', 'MDV'),
    ('me', 'MNE'),
    ('mex', 'MEX'),
    ('mexico', 'MEX'),
    ('mg', 'MAD'),
    ('mgl', 'MNG'),
    ('mgo', 'MNE'),
    ('mh', 'MHL'),
    ('mhl', 'MHL'),
    ('micronesia', 'FSM'),
    ('micronesia federated states of', 'FSM'),
    ('mk', 'MKD'),
    ('mkd', 'MKD'),
    ('ml', 'MLI'),
    ('mli', 'MLI'),
    ('mlt', 'MLT'),
    ('mm', 'MYA'),
    ('mmr', 'MYA'),
    ('mn', 'MNG'),
    ('mne', 'MNE'),
    ('mng', 'MNG'),
    ('mnp', 'NMI'),
    ('mnt', 'MSR'),
    ('mo', 'MAC'),
    ('moldova', 'MDA'),
    ('moldova the republic of', 'MDA'),
    ('mon', 'MON'),
    ('monaco', 'MON'),
    ('mongolia', 'MNG'),
    ('montenegro', 'MNE'),
    ('montserrat', 'MSR'),
    ('morocco', 'MAR'),
    ('moz', 'MOZ'),
    ('mozambique', 'MOZ'),
    ('mp', 'NMI'),
    ('mq', 'MTQ'),
    ('mr', 'MTN'),
    ('mri', 'MRI'),
    ('mrt', 'MTN'),
    ('ms', 'MSR'),
    ('msh', 'MHL'),
    ('msr', 'MSR'),
    ('mt', 'MLT'),
    ('mtn', 'MTN'),
    ('mtq', 'MTQ'),
    ('mu', 'MRI'),
    ('mus', 'MRI'),
    ('mv', 'MDV'),
    ('mw', 'MWI'),
    ('mwi', 'MWI'),
    ('mx', 'MEX'),
    ('my', 'MAS'),
    ('mya', 'MYA'),
    ('myanmar', 'MYA'),
    ('mys', 'MAS'),
    ('myt', 'MYT'),
    ('mz', 'MOZ'),
    ('na', 'NAM'),
    ('nam', 'NAM'),
    ('namibia', 'NAM'),
    ('nauru', 'NRU'),
    ('nc', 'NCL'),
    ('nca', 'NCA'),
    ('ncd', 'NCL'),
    ('ncl', 'NCL'),
    ('ne', 'NIG'),
    ('ned', 'NED'),
    ('nep', 'NEP'),
    ('nepal', 'NEP'),
    ('ner', 'NIG'),
    ('netherlands', 'NED'),
    ('netherlands the', 'NED'),
    ('new caledonia', 'NCL'),
    ('new zealand', 'NZL'),
    ('nf', 'NFK'),
    ('nfi', 'NFK'),
    ('nfk', 'NFK'),
    ('ng', 'NGA'),
    ('nga', 'RUS'),
    ('ngr', 'NGA'),
    ('nhat ban', 'JPN'),
    ('ni', 'NCA'),
    ('nic', 'NCA'),
    ('nicaragua', 'NCA'),
    ('nig', 'NIG'),
    ('niger', 'NIG'),
    ('niger the', 'NIG'),
    ('nigeria', 'NGA'),
    ('nir', 'NIR'),
    ('niu', 'NIU'),
    ('niue', 'NIU'),
    ('nl', 'NED'),
    ('nld', 'NED'),
    ('nma', 'NMI'),
    ('nmi', 'NMI'),
    ('no', 'NOR'),
    ('nor', 'NOR'),
    ('norfolk island', 'NFK'),
    ('north ireland', 'NIR'),
    ('north korea', 'PRK'),
    ('north macedonia', 'MKD'),
    ('northern ireland', 'NIR'),
    ('northern mariana islands', 'NMI'),
    ('norway', 'NOR'),
    ('np', 'NEP'),
    ('npl', 'NEP'),
    ('nr', 'NRU'),
    ('nru', 'NRU'),
    ('nu', 'NIU'),
    ('nz', 'NZL'),
    ('nzl', 'NZL'),
    ('om', 'OMA'),
    ('oma', 'OMA'),
    ('oman', 'OMA'),
    ('omn', 'OMA'),
    ('pa', 'PAN'),
    ('pak', 'PAK'),
    ('pakistan', 'PAK'),
    ('palau', 'PLW'),
    ('palestine', 'PLE'),
    ('palestine state of', 'PLE'),
    ('pan', 'PAN'),
    ('panama', 'PAN'),
    ('papua new guinea', 'PNG'),
    ('par', 'PAR'),
    ('paraguay', 'PAR'),
    ('pcn', 'PCN'),
    ('pe', 'PER'),
    ('peoples democratic republic of algeria', 'ALG'),
    ('peoples republic of bangladesh', 'BAN'),
    ('peoples republic of china', 'CHN'),
    ('per', 'PER'),
    ('peru', 'PER'),
    ('pg', 'PNG'),
    ('ph', 'PHI'),
    ('phap', 'FRA'),
    ('phi', 'PHI'),
    ('philippines', 'PHI'),
    ('philippines the', 'PHI'),
    ('phl', 'PHI'),
    ('pitcairn', 'PCN'),
    ('pk', 'PAK'),
    ('pl', 'POL'),
    ('ple', 'PLE'),
    ('plurinational state of bolivia', 'BOL'),
    ('plw', 'PLW'),
    ('pm', 'SPM'),
    ('pn', 'PCN'),
    ('png', 'PNG'),
    ('pol', 'POL'),
    ('poland', 'POL'),
    ('por', 'POR'),
    ('portugal', 'POR'),
    ('portuguese republic', 'POR'),
    ('pr', 'PUR'),
    ('premier league uk', 'ENG'),
    ('pri', 'PUR'),
    ('principality of andorra', 'AND'),
    ('principality of liechtenstein', 'LIE'),
    ('principality of monaco', 'MON'),
    ('prk', 'PRK'),
    ('prt', 'POR'),
    ('pry', 'PAR'),
    ('ps', 'PLE'),
    ('pse', 'PLE'),
    ('pt', 'POR'),
    ('puerto rico', 'PUR'),
    ('pur', 'PUR'),
    ('pw', 'PLW'),
    ('py', 'PAR'),
    ('qa', 'QAT'),
    ('qat', 'QAT'),
    ('qatar', 'QAT'),
    ('re', 'REU'),
    ('republic of albania', 'ALB'),
    ('republic of angola', 'ANG'),
    ('republic of armenia', 'ARM'),
    ('republic of austria', 'AUT'),
    ('republic of azerbaijan', 'AZE'),
    ('republic of belarus', 'BLR'),
    ('republic of benin', 'BEN'),
    ('republic of botswana', 'BOT'),
    ('republic of bulgaria', 'BUL'),
    ('republic of burundi', 'BDI'),
    ('republic of cabo verde', 'CPV'),
    ('republic of cameroon', 'CMR'),
    ('republic of chad', 'CHA'),
    ('republic of chile', 'CHI'),
    ('republic of colombia', 'COL'),
    ('republic of costa rica', 'CRC'),
    ('republic of croatia', 'CRO'),
    ('republic of cuba', 'CUB'),
    ('republic of cyprus', 'CYP'),
    ('republic of djibouti', 'DJI'),
    ('republic of ecuador', 'ECU'),
    ('republic of el salvador', 'SLV'),
    ('republic of equatorial guinea', 'EQG'),
    ('republic of estonia', 'EST'),
    ('republic of fiji', 'FIJ'),
    ('republic of finland', 'FIN'),
    ('republic of ghana', 'GHA'),
    ('republic of guatemala', 'GUA'),
    ('republic of guinea', 'GUI'),
    ('republic of guinea bissau', 'GNB'),
    ('republic of haiti', 'HAI'),
    ('republic of honduras', 'HON'),
    ('republic of iceland', 'ISL'),
    ('republic of india', 'IND'),
    ('republic of indonesia', 'IDN'),
    ('republic of iraq', 'IRQ'),
    ('republic of italy', 'ITA'),
    ('republic of kazakhstan', 'KAZ'),
    ('republic of kenya', 'KEN'),
    ('republic of kiribati', 'KIR'),
    ('republic of korea', 'KOR'),
    ('republic of korea the', 'KOR'),
    ('republic of latvia', 'LVA'),
    ('republic of liberia', 'LBR'),
    ('republic of lithuania', 'LTU'),
    ('republic of madagascar', 'MAD'),
    ('republic of malawi', 'MWI'),
    ('republic of maldives', 'MDV'),
    ('republic of mali', 'MLI'),
    ('republic of malta', 'MLT'),
    ('republic of mauritius', 'MRI'),
    ('republic of moldova', 'MDA'),
    ('republic of moldova the', 'MDA'),
    ('republic of mozambique', 'MOZ'),
    ('republic of namibia', 'NAM'),
    ('republic of nauru', 'NRU'),
    ('republic of nicaragua', 'NCA'),
    ('republic of north macedonia', 'MKD'),
    ('republic of palau', 'PLW'),
    ('republic of panama', 'PAN'),
    ('republic of paraguay', 'PAR'),
    ('republic of peru', 'PER'),
    ('republic of poland', 'POL'),
    ('republic of rwanda', 'RWA'),
    ('republic of san marino', 'SMR'),
    ('republic of senegal', 'SEN'),
    ('republic of serbia', 'SRB'),
    ('republic of seychelles', 'SEY'),
    ('republic of sierra leone', 'SLE'),
    ('republic of singapore', 'SGP'),
    ('republic of slovenia', 'SVN'),
    ('republic of south africa', 'RSA'),
    ('republic of south sudan', 'SSD'),
    ('republic of suriname', 'SUR'),
    ('republic of tajikistan', 'TJK'),
    ('republic of the congo', 'CGO'),
    ('republic of the gambia', 'GAM'),
    ('republic of the marshall islands', 'MHL'),
    ('republic of the niger', 'NIG'),
    ('republic of the philippines', 'PHI'),
    ('republic of the sudan', 'SDN'),
    ('republic of the union of myanmar', 'MYA'),
    ('republic of trinidad and tobago', 'TRI'),
    ('republic of tunisia', 'TUN'),
    ('republic of uganda', 'UGA'),
    ('republic of uzbekistan', 'UZB'),
    ('republic of vanuatu', 'VAN'),
    ('republic of yemen', 'YEM'),
    ('republic of zambia', 'ZAM'),
    ('republic of zimbabwe', 'ZIM'),
    ('reu', 'REU'),
    ('reunion', 'REU'),
    ('ro', 'ROU'),
    ('romania', 'ROU'),
    ('rou', 'ROU'),
    ('rs', 'SRB'),
    ('rsa', 'RSA'),
    ('ru', 'RUS'),
    ('rus', 'RUS'),
    ('russia', 'RUS'),
    ('russian federation', 'RUS'),
    ('russian federation the', 'RUS'),
    ('rw', 'RWA'),
    ('rwa', 'RWA'),
    ('rwanda', 'RWA'),
    ('sa', 'KSA'),
    ('sah', 'SAH'),
    ('saint helena', 'SHN'),
    ('saint helena ascension and tristan da cunha', 'SHN'),
    ('saint kitts and nevis', 'SKN'),
    ('saint lucia', 'LCA'),
    ('saint pierre and miquelon', 'SPM'),
    ('saint vincent and the grenadines', 'VIN'),
    ('sam', 'SAM'),
    ('samoa', 'SAM'),
    ('san marino', 'SMR'),
    ('sao tome and principe', 'STP'),
    ('sau', 'KSA'),
    ('saudi arabia', 'KSA'),
    ('sb', 'SOL'),
    ('sc', 'SEY'),
    ('sco', 'SCO'),
    ('scotland', 'SCO'),
    ('sd', 'SDN'),
    ('sdn', 'SDN'),
    ('se', 'SWE'),
    ('sen', 'SEN'),
    ('senegal', 'SEN'),
    ('serbia', 'SRB'),
    ('sey', 'SEY'),
    ('seychelles', 'SEY'),
    ('sg', 'SGP'),
    ('sgp', 'SGP'),
    ('sh', 'SHN'),
    ('shn', 'SHN'),
    ('si', 'SVN'),
    ('sierra leone', 'SLE'),
    ('sin', 'SGP'),
    ('singapore', 'SGP'),
    ('sk', 'SVK'),
    ('skn', 'SKN'),
    ('sl', 'SLE'),
    ('slb', 'SOL'),
    ('sle', 'SLE'),
    ('slo', 'SVN'),
    ('slovak republic', 'SVK'),
    ('slovakia', 'SVK'),
    ('slovenia', 'SVN'),
    ('slv', 'SLV'),
    ('sm', 'SMR'),
    ('smr', 'SMR'),
    ('sn', 'SEN'),
    ('so', 'SOM'),
    ('socialist republic of viet nam', 'VIE'),
    ('sol', 'SOL'),
    ('solomon islands', 'SOL'),
    ('som', 'SOM'),
    ('somalia', 'SOM'),
    ('south africa', 'RSA'),
    ('south korea', 'KOR'),
    ('south sudan', 'SSD'),
    ('spain', 'ESP'),
    ('spm', 'SPM'),
    ('sr', 'SUR'),
    ('srb', 'SRB'),
    ('sri', 'SRI'),
    ('sri lanka', 'SRI'),
    ('ss', 'SSD'),
    ('ssd', 'SSD'),
    ('st', 'STP'),
    ('st helena', 'SHN'),
    ('st kitts and nevis', 'SKN'),
    ('st lucia', 'LCA'),
    ('st pierre and miquelon', 'SPM'),
    ('st vincent and grenadines', 'VIN'),
    ('state of eritrea', 'ERI'),
    ('state of israel', 'ISR'),
    ('state of kuwait', 'KUW'),
    ('state of libya', 'LBY'),
    ('state of palestine', 'PLE'),
    ('state of palestine the', 'PLE'),
    ('state of qatar', 'QAT'),
    ('stp', 'STP'),
    ('sud', 'SDN'),
    ('sudan', 'SDN'),
    ('sudan the', 'SDN'),
    ('sui', 'SUI'),
    ('sultanate of oman', 'OMA'),
    ('sur', 'SUR'),
    ('suriname', 'SUR'),
    ('sv', 'SLV'),
    ('svk', 'SVK'),
    ('svn', 'SVN'),
    ('swe', 'SWE'),
    ('sweden', 'SWE'),
    ('swiss confederation', 'SUI'),
    ('switzerland', 'SUI'),
    ('swz', 'SWZ'),
    ('sy', 'SYR'),
    ('syc', 'SEY'),
    ('syr', 'SYR'),
    ('syria', 'SYR'),
    ('syrian arab republic', 'SYR'),
    ('syrian arab republic the', 'SYR'),
    ('sz', 'SWZ'),
    ('taiwan', 'TPE'),
    ('taiwan province of china', 'TPE'),
    ('tajikistan', 'TJK'),
    ('tan', 'TAN'),
    ('tanzania', 'TAN'),
    ('tanzania united republic of', 'TAN'),
    ('tay ban nha', 'ESP'),
    ('tc', 'TCA'),
    ('tca', 'TCA'),
    ('tcd', 'CHA'),
    ('td', 'CHA'),
    ('tg', 'TOG'),
    ('tga', 'TGA'),
    ('tgo', 'TOG'),
    ('th', 'THA'),
    ('tha', 'THA'),
    ('thai lan', 'THA'),
    ('thailand', 'THA'),
    ('the arab republic of egypt', 'EGY'),
    ('the argentine republic', 'ARG'),
    ('the bolivarian republic of venezuela', 'VEN'),
    ('the central african republic', 'CTA'),
    ('the co operative republic of guyana', 'GUY'),
    ('the commonwealth of dominica', 'DMA'),
    ('the commonwealth of the bahamas', 'BAH'),
    ('the cook islands', 'COK'),
    ('the czech republic', 'CZE'),
    ('the democratic peoples republic of korea', 'PRK'),
    ('the democratic republic of sao tome and principe', 'STP'),
    ('the democratic republic of the congo', 'COD'),
    ('the democratic republic of timor leste', 'TLS'),
    ('the democratic socialist republic of sri lanka', 'SRI'),
    ('the dominican republic', 'DOM'),
    ('the eastern republic of uruguay', 'URU'),
    ('the federal democratic republic of ethiopia', 'ETH'),
    ('the federal republic of germany', 'GER'),
    ('the federal republic of nigeria', 'NGA'),
    ('the federal republic of somalia', 'SOM'),
    ('the federated states of micronesia', 'FSM'),
    ('the federative republic of brazil', 'BRA'),
    ('the french republic', 'FRA'),
    ('the gabonese republic', 'GAB'),
    ('the grand duchy of luxembourg', 'LUX'),
    ('the hashemite kingdom of jordan', 'JOR'),
    ('the hellenic republic', 'GRE'),
    ('the holy see', 'VAT'),
    ('the independent state of papua new guinea', 'PNG'),
    ('the independent state of samoa', 'SAM'),
    ('the islamic republic of afghanistan', 'AFG'),
    ('the islamic republic of iran', 'IRN'),
    ('the islamic republic of mauritania', 'MTN'),
    ('the islamic republic of pakistan', 'PAK'),
    ('the kingdom of bahrain', 'BHR'),
    ('the kingdom of belgium', 'BEL'),
    ('the kingdom of bhutan', 'BHU'),
    ('the kingdom of cambodia', 'CAM'),
    ('the kingdom of denmark', 'DEN'),
    ('the kingdom of eswatini', 'SWZ'),
    ('the kingdom of lesotho', 'LES'),
    ('the kingdom of morocco', 'MAR'),
    ('the kingdom of norway', 'NOR'),
    ('the kingdom of saudi arabia', 'KSA'),
    ('the kingdom of spain', 'ESP'),
    ('the kingdom of sweden', 'SWE'),
    ('the kingdom of thailand', 'THA'),
    ('the kingdom of the netherlands', 'NED'),
    ('the kingdom of tonga', 'TGA'),
    ('the kyrgyz republic', 'KGZ'),
    ('the lao peoples democratic republic', 'LAO'),
    ('the lebanese republic', 'LBN'),
    ('the peoples democratic republic of algeria', 'ALG'),
    ('the peoples republic of bangladesh', 'BAN'),
    ('the peoples republic of china', 'CHN'),
    ('the plurinational state of bolivia', 'BOL'),
    ('the portuguese republic', 'POR'),
    ('the principality of andorra', 'AND'),
    ('the principality of liechtenstein', 'LIE'),
    ('the principality of monaco', 'MON'),
    ('the republic of albania', 'ALB'),
    ('the republic of angola', 'ANG'),
    ('the republic of armenia', 'ARM'),
    ('the republic of austria', 'AUT'),
    ('the republic of azerbaijan', 'AZE'),
    ('the republic of belarus', 'BLR'),
    ('the republic of benin', 'BEN'),
    ('the republic of botswana', 'BOT'),
    ('the republic of bulgaria', 'BUL'),
    ('the republic of burundi', 'BDI'),
    ('the republic of cabo verde', 'CPV'),
    ('the republic of cameroon', 'CMR'),
    ('the republic of chad', 'CHA'),
    ('the republic of chile', 'CHI'),
    ('the republic of colombia', 'COL'),
    ('the republic of costa rica', 'CRC'),
    ('the republic of croatia', 'CRO'),
    ('the republic of cuba', 'CUB'),
    ('the republic of cyprus', 'CYP'),
    ('the republic of djibouti', 'DJI'),
    ('the republic of ecuador', 'ECU'),
    ('the republic of el salvador', 'SLV'),
    ('the republic of equatorial guinea', 'EQG'),
    ('the republic of estonia', 'EST'),
    ('the republic of fiji', 'FIJ'),
    ('the republic of finland', 'FIN'),
    ('the republic of ghana', 'GHA'),
    ('the republic of guatemala', 'GUA'),
    ('the republic of guinea', 'GUI'),
    ('the republic of guinea bissau', 'GNB'),
    ('the republic of haiti', 'HAI'),
    ('the republic of honduras', 'HON'),
    ('the republic of iceland', 'ISL'),
    ('the republic of india', 'IND'),
    ('the republic of indonesia', 'IDN'),
    ('the republic of iraq', 'IRQ'),
    ('the republic of italy', 'ITA'),
    ('the republic of kazakhstan', 'KAZ'),
    ('the republic of kenya', 'KEN'),
    ('the republic of kiribati', 'KIR'),
    ('the republic of korea', 'KOR'),
    ('the republic of latvia', 'LVA'),
    ('the republic of liberia', 'LBR'),
    ('the republic of lithuania', 'LTU'),
    ('the republic of madagascar', 'MAD'),
    ('the republic of malawi', 'MWI'),
    ('the republic of maldives', 'MDV'),
    ('the republic of mali', 'MLI'),
    ('the republic of malta', 'MLT'),
    ('the republic of mauritius', 'MRI'),
    ('the republic of moldova', 'MDA'),
    ('the republic of mozambique', 'MOZ'),
    ('the republic of namibia', 'NAM'),
    ('the republic of nauru', 'NRU'),
    ('the republic of nicaragua', 'NCA'),
    ('the republic of north macedonia', 'MKD'),
    ('the republic of palau', 'PLW'),
    ('the republic of panama', 'PAN'),
    ('the republic of paraguay', 'PAR'),
    ('the republic of peru', 'PER'),
    ('the republic of poland', 'POL'),
    ('the republic of rwanda', 'RWA'),
    ('the republic of san marino', 'SMR'),
    ('the republic of senegal', 'SEN'),
    ('the republic of serbia', 'SRB'),
    ('the republic of seychelles', 'SEY'),
    ('the republic of sierra leone', 'SLE'),
    ('the republic of singapore', 'SGP'),
    ('the republic of slovenia', 'SVN'),
    ('the republic of south africa', 'RSA'),
    ('the republic of south sudan', 'SSD'),
    ('the republic of suriname', 'SUR'),
    ('the republic of tajikistan', 'TJK'),
    ('the republic of the congo', 'CGO'),
    ('the republic of the gambia', 'GAM'),
    ('the republic of the marshall islands', 'MHL'),
    ('the republic of the niger', 'NIG'),
    ('the republic of the philippines', 'PHI'),
    ('the republic of the sudan', 'SDN'),
    ('the republic of the union of myanmar', 'MYA'),
    ('the republic of trinidad and tobago', 'TRI'),
    ('the republic of tunisia', 'TUN'),
    ('the republic of uganda', 'UGA'),
    ('the republic of uzbekistan', 'UZB'),
    ('the republic of vanuatu', 'VAN'),
    ('the republic of yemen', 'YEM'),
    ('the republic of zambia', 'ZAM'),
    ('the republic of zimbabwe', 'ZIM'),
    ('the russian federation', 'RUS'),
    ('the slovak republic', 'SVK'),
    ('the socialist republic of viet nam', 'VIE'),
    ('the state of eritrea', 'ERI'),
    ('the state of israel', 'ISR'),
    ('the state of kuwait', 'KUW'),
    ('the state of libya', 'LBY'),
    ('the state of palestine', 'PLE'),
    ('the state of qatar', 'QAT'),
    ('the sultanate of oman', 'OMA'),
    ('the swiss confederation', 'SUI'),
    ('the syrian arab republic', 'SYR'),
    ('the togolese republic', 'TOG'),
    ('the union of the comoros', 'COM'),
    ('the united arab emirates', 'UAE'),
    ('the united mexican states', 'MEX'),
    ('the united republic of tanzania', 'TAN'),
    ('the united states of america', 'USA'),
    ('timor leste', 'TLS'),
    ('tj', 'TJK'),
    ('tjk', 'TJK'),
    ('tk', 'TKL'),
    ('tkl', 'TKL'),
    ('tkm', 'TKM'),
    ('tks', 'TCA'),
    ('tl', 'TLS'),
    ('tls', 'TLS'),
    ('tm', 'TKM'),
    ('tn', 'TUN'),
    ('to', 'TGA'),
    ('tog', 'TOG'),
    ('togo', 'TOG'),
    ('togolese republic', 'TOG'),
    ('tokelau', 'TKL'),
    ('ton', 'TGA'),
    ('tonga', 'TGA'),
    ('tpe', 'TPE'),
    ('tr', 'TUR'),
    ('tri', 'TRI'),
    ('trinidad and tobago', 'TRI'),
    ('trung quoc', 'CHN'),
    ('tt', 'TRI'),
    ('tto', 'TRI'),
    ('tun', 'TUN'),
    ('tunisia', 'TUN'),
    ('tur', 'TUR'),
    ('turkey', 'TUR'),
    ('turkiye', 'TUR'),
    ('turkmenistan', 'TKM'),
    ('turks and caicos islands', 'TCA'),
    ('tuv', 'TUV'),
    ('tuvalu', 'TUV'),
    ('tv', 'TUV'),
    ('tw', 'TPE'),
    ('twn', 'TPE'),
    ('tz', 'TAN'),
    ('tza', 'TAN'),
    ('u k', 'ENG'),
    ('u s virgin islands', 'VIR'),
    ('ua', 'UKR'),
    ('uae', 'UAE'),
    ('ug', 'UGA'),
    ('uga', 'UGA'),
    ('uganda', 'UGA'),
    ('uk', 'ENG'),
    ('ukr', 'UKR'),
    ('ukraine', 'UKR'),
    ('union of the comoros', 'COM'),
    ('united arab emirates', 'UAE'),
    ('united arab emirates the', 'UAE'),
    ('united kingdom', 'ENG'),
    ('united mexican states', 'MEX'),
    ('united republic of tanzania', 'TAN'),
    ('united republic of tanzania the', 'TAN'),
    ('united states of america', 'USA'),
    ('united states of america the', 'USA'),
    ('united states virgin islands', 'VIR'),
    ('uru', 'URU'),
    ('uruguay', 'URU'),
    ('ury', 'URU'),
    ('us', 'USA'),
    ('usa', 'USA'),
    ('uy', 'URU'),
    ('uz', 'UZB'),
    ('uzb', 'UZB'),
    ('uzbekistan', 'UZB'),
    ('va', 'VAT'),
    ('van', 'VAN'),
    ('vanuatu', 'VAN'),
    ('vat', 'VAT'),
    ('vatican city', 'VAT'),
    ('vc', 'VIN'),
    ('vct', 'VIN'),
    ('ve', 'VEN'),
    ('ven', 'VEN'),
    ('venezuela', 'VEN'),
    ('venezuela bolivarian republic of', 'VEN'),
    ('vg', 'VGB'),
    ('vgb', 'VGB'),
    ('vi', 'VIR'),
    ('vie', 'VIE'),
    ('viet', 'VIE'),
    ('viet nam', 'VIE'),
    ('vietnam', 'VIE'),
    ('vin', 'VIN'),
    ('vir', 'VIR'),
    ('virgin islands', 'VIR'),
    ('virgin islands british', 'VGB'),
    ('virgin islands u s', 'VIR'),
    ('vn', 'VIE'),
    ('vnm', 'VIE'),
    ('vu', 'VAN'),
    ('vut', 'VAN'),
    ('waf', 'WLF'),
    ('wal', 'WAL'),
    ('wales', 'WAL'),
    ('wallis and futuna', 'WLF'),
    ('wallis and futuna islands', 'WLF'),
    ('western sahara', 'SAH'),
    ('wf', 'WLF'),
    ('wlf', 'WLF'),
    ('ws', 'SAM'),
    ('wsm', 'SAM'),
    ('ye', 'YEM'),
    ('yem', 'YEM'),
    ('yemen', 'YEM'),
    ('yt', 'MYT'),
    ('za', 'RSA'),
    ('zaf', 'RSA'),
    ('zam', 'ZAM'),
    ('zambia', 'ZAM'),
    ('zim', 'ZIM'),
    ('zimbabwe', 'ZIM'),
    ('zm', 'ZAM'),
    ('zmb', 'ZAM'),
    ('zw', 'ZIM'),
    ('zwe', 'ZIM');

update leagues l
join league_country_code_short_map m
  on trim(regexp_replace(
      replace(replace(replace(lower(l.country), '&', ' and '), '''', ''), '’', ''),
      '[^0-9a-z]+',
      ' '
  )) = m.country_name
set l.country_code_short = m.country_code_short
where l.country is not null
  and trim(l.country) <> ''
  and (l.country_code_short is null or l.country_code_short <> m.country_code_short);

drop temporary table league_country_code_short_map;
