import React, { useState } from 'react';
import { Image, Modal, Pressable, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { banks, cards, money } from './data';
import { Gauge, TrendChart, Allocation } from './charts';
import { colors as c } from './theme';
import { useDemo } from './store';
import { Badge, Button, Card, Chips, Dialog, Empty, Field, FitValue, go, Icon, Info, Metric, Progress, Row, Screen, Section, T, useNotice } from './ui';

export function BankCard({ bank }: { bank: typeof banks[number] }) {
  return <Card><Row><View style={{ width: 32, height: 32, borderRadius: 16, backgroundColor: bank.color + '22', justifyContent: 'center', alignItems: 'center' }}><T size={12} bold color={bank.color}>{bank.short}</T></View><View style={{ flex: 1 }}><T bold>{bank.name}</T><T size={10} color={c.muted}>{bank.cards} thẻ ({bank.id === 'tcb' ? 'Signature, Everyday' : bank.id === 'vpb' ? 'StepUp Mastercard' : 'Cash Back'})</T></View><Badge>{(bank.debt / bank.limit * 100).toFixed(1)}%</Badge></Row><Row><Metric label="HẠN MỨC CHUNG" value={money(bank.limit)} color={c.text} /><Metric label="DƯ NỢ HIỆN TẠI" value={money(bank.debt)} /></Row><Progress value={bank.debt / bank.limit * 100} color={bank.color} /></Card>;
}
function PlasticCard({ card }: { card: typeof cards[number] }) {
  const bank = banks.find(b => b.id === card.bank)!;
  return <LinearGradient colors={card.bank === 'vpb' ? ['#0a2324', '#10383b', '#1e5358'] : card.bank === 'vib' ? ['#1b1c38', '#24264f', '#342e61'] : ['#0a192f', '#0f2744', '#1a3a5c']} style={{ padding: 16, borderRadius: 16, gap: 12 }}>
    <Row style={{ gap: 4 }}><T size={10} style={{ flex: 1 }}>{bank.name.toUpperCase()} <T size={8} color={c.muted}> | {card.name.toUpperCase()}</T></T><T size={8} color={c.primary}>• Đang hoạt động</T></Row><Row style={{ justifyContent: 'space-between' }}><View style={{ width: 27, height: 23, borderRadius: 5, backgroundColor: '#f6d267', borderWidth: 2, borderColor: '#dab552' }} /><Icon name="wifi-outline" size={16} /></Row><T size={15} style={{ letterSpacing: 2 }}>•••• •••• •••• {card.id}</T><Row style={{ justifyContent: 'space-between', gap: 4 }}><T size={7}>NGUYEN HOANG HAI • {card.expiry}</T><T size={13} bold color={c.primary}>{card.id === '4190' || card.bank === 'vpb' ? '●●' : 'VISA'}</T></Row>
  </LinearGradient>;
}
export function Dashboard() {
  const { notify, dialog } = useNotice(); const { state } = useDemo(); const displayBanks = banks.map(b => ({ ...b, ...state.creditConfig?.banks[b.id] })); const debt = displayBanks.reduce((n, b) => n + b.debt, 0); const limit = displayBanks.reduce((n, b) => n + b.limit, 0);
  return <Screen title="Thẻ tín dụng">
    <Row><View style={{ flex: 1, gap: 2 }}><T size={11} color={c.primary}>• HỒ SƠ TÀI CHÍNH ĐỒNG BỘ</T><T size={20} bold>Chào buổi sáng, Minh Triết</T><T size={11} color={c.muted}>4 thẻ tín dụng đang hoạt động bình thường</T></View><Icon name="shield-checkmark-outline" /></Row>
    <Card tint style={{ padding: 18, gap: 12 }}><View style={{ gap: 4 }}><Row style={{ justifyContent: 'space-between', gap: 4 }}><T size={11} color={c.muted}>Tổng dư nợ hiện tại</T><Badge>◴ {Math.round(debt / limit * 100)}% Sử dụng</Badge></Row><T size={28} bold style={{ letterSpacing: -1 }}>{money(debt)}</T></View><View style={{ gap: 6 }}><Row><T size={11} color={c.muted} style={{ flex: 1 }}>Tỷ lệ sử dụng hạn mức (Credit Utilization)</T><T size={11} color={c.primary} bold>{(debt / limit * 100).toFixed(1)}% <T size={10} color={c.muted}>(An toàn)</T></T></Row><Progress value={debt / limit * 100} /></View><Row><Metric label="Hạn mức khả dụng" value={money(limit - debt)} /><Metric label="Tổng hạn mức" value={money(limit)} color={c.text} /></Row><Info>Dữ liệu tổng hợp theo cấp ngân hàng, không nhân đôi khi một ngân hàng phát hành nhiều thẻ.</Info></Card>
    <Section title="Tác vụ nhanh" action="3 phím tắt" onPress={() => go('cards')} /><Row style={{ alignItems: 'stretch', gap: 10 }}>{([{ label: 'Thẻ của tôi', icon: 'card-outline', target: 'cards' }, { label: 'Ưu đãi & Hoàn tiền', icon: 'gift-outline', target: 'benefits' }, { label: 'Điều chỉnh số dư', icon: 'options-outline', target: 'cards' }] as const).map(item => <Pressable key={item.label} accessibilityRole="button" onPress={() => go(item.target)} style={{ flex: 1, minHeight: 96, padding: 12, backgroundColor: c.surface, borderRadius: 24, alignItems: 'center', justifyContent: 'center', gap: 8 }}><View style={{ width: 40, height: 40, backgroundColor: '#1c3041', borderRadius: 20, alignItems: 'center', justifyContent: 'center' }}><Icon name={item.icon} color={item.target === 'benefits' ? c.lavender : c.primary} size={20} /></View><T size={11} style={{ textAlign: 'center' }}>{item.label}</T></Pressable>)}</Row>
    <Section title="Kỳ sao kê & Hạn sắp tới" action="Tháng 10/2024" onPress={() => go('credit-stats')} />
    <Card><Row><Icon name="calendar-outline" /><View style={{ flex: 1 }}><T size={11} color={c.muted}>Techcombank Visa Signature</T><T size={13} bold>Hạn thanh toán: 25/10/2024</T></View><Badge tone="error">Còn 5 ngày</Badge></Row><Row><Metric label="Dư nợ tối thiểu" value={money(5000000)} /><Metric label="Toàn bộ dư nợ kỳ này" value={money(28400000)} color={c.text} /></Row><Button label="Thanh toán ngay" icon="wallet-outline" onPress={() => notify('Thanh toán đang được mô phỏng. Không phát sinh giao dịch thật.')} /></Card>
    <Card><Row><Icon name="calendar-outline" /><View style={{ flex: 1 }}><T size={12} bold>VPBank StepUp Mastercard</T><T size={10} color={c.muted}>Chốt sao kê vào ngày 20/10/2024</T></View><Badge>Chưa lập hóa đơn</Badge></Row></Card>
    <Section title="Hạn mức theo Ngân hàng" action="3 ngân hàng" onPress={() => go('credit-stats')} />{displayBanks.map(bank => <BankCard key={bank.id} bank={bank} />)}
    <Section title="Bộ sưu tập thẻ phát hành" /><Row style={{ alignItems: 'stretch', gap: 10 }}>{[require('../assets/reference/dashboard-0.png'), require('../assets/reference/dashboard-1.png')].map((source, i) => <Pressable key={i} onPress={() => go('cards')} accessibilityRole="button" style={{ flex: 1, overflow: 'hidden', borderRadius: 22 }}><Image source={source} style={{ width: '100%', height: 104 }} /><View style={{ position: 'absolute', left: 8, bottom: 8, right: 4 }}><T size={10} bold>{i ? 'VPBank StepUp' : 'Techcombank Signature'}</T></View></Pressable>)}</Row>{dialog}
  </Screen>;
}
export function MyCards() {
  const { state, update } = useDemo(); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all'); const [freeze, setFreeze] = useState(''); const [adjust, setAdjust] = useState(''); const [limit, setLimit] = useState(''); const [debt, setDebt] = useState(''); const [reason, setReason] = useState(''); const [error, setError] = useState(''); const { notify, dialog } = useNotice();
  const overrides = state.creditConfig?.banks || {}; const [adjustCard, setAdjustCard] = useState('');
  const shown = cards.filter(card => (filter === 'all' || filter === 'active' && !state.frozenCards.includes(card.id) || filter === 'frozen' && state.frozenCards.includes(card.id) || filter === card.bank) && `${card.name} ${card.id} ${banks.find(b => b.id === card.bank)?.name}`.toLowerCase().includes(query.toLowerCase()));
  return <Screen title="Thẻ của tôi" back><Row><View style={{ flex: 1 }}><Field label="Tìm thẻ" placeholder="Tên thẻ, số thẻ, ngân hàng" value={query} onChangeText={setQuery} /></View><Button label="Thêm thẻ" icon="add" onPress={() => notify('Thêm thẻ được mô phỏng. Không liên kết thẻ thật.')} /></Row><Chips values={[{ label: 'Tất cả (4)', value: 'all' }, { label: `Đang hoạt động (${4 - state.frozenCards.length})`, value: 'active' }, { label: `Đã tạm khóa (${state.frozenCards.length})`, value: 'frozen' }, ...banks.map(b => ({ label: b.name, value: b.id }))]} value={filter} onChange={setFilter} />
    <Card tint><Row><Icon name="card-outline" size={18} /><T size={11} style={{ flex: 1 }}>Tổng hạn mức khả dụng</T><Badge>3 Ngân Hàng</Badge></Row><T size={26} bold>{money(banks.reduce((n, b) => n + (overrides[b.id]?.limit ?? b.limit) - (overrides[b.id]?.debt ?? b.debt), 0))}</T><T size={10} color={c.muted}>Tổng dư nợ hiện tại: {money(banks.reduce((n, b) => n + (overrides[b.id]?.debt ?? b.debt), 0))} • Hạn mức gộp {money(banks.reduce((n, b) => n + (overrides[b.id]?.limit ?? b.limit), 0))}</T></Card>
    {!shown.length ? <Empty title="Không tìm thấy thẻ" /> : banks.filter(b => shown.some(card => card.bank === b.id)).map(b => <View key={b.id} style={{ gap: 12 }}><Card style={{ padding: 12 }}><Row><Badge>{b.short}</Badge><View style={{ flex: 1 }}><T size={13} bold>{b.name} <T size={10} color={c.muted}>{b.cards} Thẻ</T></T><T size={9} color={c.muted}>Hạn mức chung: {money(overrides[b.id]?.limit ?? b.limit)} • Nợ: {money(overrides[b.id]?.debt ?? b.debt)}</T></View><Pressable accessibilityRole="button" accessibilityLabel={`Điều chỉnh ${b.name}`} onPress={() => { setAdjustCard(''); setAdjust(b.id); setLimit(String(overrides[b.id]?.limit ?? b.limit)); setDebt(String(overrides[b.id]?.debt ?? b.debt)); setError(''); }} style={{ padding: 10 }}><Icon name="pencil-outline" size={16} /></Pressable></Row></Card>{shown.filter(card => card.bank === b.id).map(card => <Card key={card.id} style={{ padding: 12, gap: 12 }}><PlasticCard card={card} />{state.frozenCards.includes(card.id) ? <Badge tone="warning">Đã tạm khóa</Badge> : null}<Row><View style={{ flex: 1 }}><T size={9} color={c.muted}>Hạn mức riêng</T><T size={12} bold>{money(state.creditConfig?.cards[card.id] ?? (card.id === '8829' ? 100000000 : 50000000))}</T></View><View style={{ flex: 1 }}><T size={9} color={c.muted}>Dư nợ hiện tại</T><T size={12} bold color={c.primary}>{money(card.debt)}</T></View></Row><Row style={{ gap: 6 }}>{[{ label: 'Hạn mức', icon: 'options-outline' as const, run: () => { setAdjustCard(card.id); setAdjust(b.id); setLimit(String(state.creditConfig?.cards[card.id] ?? (card.id === '8829' ? 100000000 : 50000000))); setDebt(String(b.debt)); setReason('Điều chỉnh hạn mức thẻ'); setError(''); } }, { label: 'Lịch sử', icon: 'time-outline' as const, run: () => notify((state.creditConfig?.audit.filter(a => a.target === card.id || a.target === b.id).map(a => `${a.date} • ${a.reason}`).join('\n') || 'Đồng bộ sao kê +12.450.000 đ; Thanh toán dư nợ −20.000.000 đ; Hoàn tiền Shopee −650.000 đ.')) }, { label: state.frozenCards.includes(card.id) ? 'Mở khóa' : 'Tạm khóa', icon: 'lock-closed-outline' as const, run: () => setFreeze(card.id) }].map(item => <Pressable key={item.label} accessibilityRole="button" onPress={item.run} style={{ flex: 1, flexDirection: 'row', gap: 4, minHeight: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: '#192538' }}><Icon name={item.icon} size={12} /><T size={9}>{item.label}</T></Pressable>)}</Row></Card>)}</View>)}
    <Info>Bảo mật chuẩn mã hóa Glacier 256-bit • Kira Safeguard</Info>
    <Modal visible={!!adjust} transparent animationType="fade" onRequestClose={() => setAdjust('')}><View style={{ flex: 1, backgroundColor: '#000a', justifyContent: 'center', padding: 24 }}><Card><T size={20} bold>Điều chỉnh {adjustCard ? `hạn mức thẻ • ${adjustCard}` : banks.find(b => b.id === adjust)?.name}</T><Field label={adjustCard ? "Hạn mức thẻ riêng biệt (VND)" : "Hạn mức chung cấp ngân hàng"} value={limit} onChangeText={setLimit} keyboardType="numeric" />{!adjustCard ? <Field label="Dư nợ thực tế cần đồng bộ" value={debt} onChangeText={setDebt} keyboardType="numeric" /> : null}<Field label="Lý do điều chỉnh" value={reason} onChangeText={setReason} />{error ? <T color={c.error}>{error}</T> : null}<Button label="Lưu thay đổi" onPress={() => { if (!Number.isFinite(Number(limit)) || !Number.isFinite(Number(debt)) || Number(limit) <= 0 || Number(debt) < 0 || !reason.trim()) { setError('Nhập hạn mức hợp lệ, dư nợ không âm và lý do.'); return; } if (adjustCard && Number(limit) > (overrides[adjust]?.limit ?? banks.find(b => b.id === adjust)!.limit)) { setError('Hạn mức riêng không được vượt hạn mức chung của ngân hàng.'); return; } update(s => { const config = s.creditConfig || { banks: {}, cards: {}, audit: [] }; return { ...s, creditConfig: { banks: adjustCard ? config.banks : { ...config.banks, [adjust]: { limit: Number(limit), debt: Number(debt) } }, cards: adjustCard ? { ...config.cards, [adjustCard]: Number(limit) } : config.cards, audit: [...config.audit, { target: adjustCard || adjust, reason: reason.trim(), date: new Date().toISOString() }] } }; }); setAdjust(''); notify('Đã lưu điều chỉnh trên thiết bị.'); }} /><Button label="Hủy" kind="secondary" onPress={() => setAdjust('')} /></Card></View></Modal>
    <Dialog visible={!!freeze} title="Thay đổi trạng thái thẻ?" message="Thao tác cập nhật trạng thái thẻ mẫu trên thiết bị." onClose={() => setFreeze('')} onConfirm={() => { update(s => ({ ...s, frozenCards: s.frozenCards.includes(freeze) ? s.frozenCards.filter(id => id !== freeze) : [...s.frozenCards, freeze] })); setFreeze(''); }} />{dialog}
  </Screen>;
}
export function Benefits() {
  const { state, update } = useDemo(); const [cap, setCap] = useState(String(state.cashbackCap)); const [mcc, setMcc] = useState(''); const [error, setError] = useState(''); const [editingCap, setEditingCap] = useState(false); const { notify, dialog } = useNotice();
  function save() { const n = Number(cap); if (!Number.isFinite(n) || n <= 0) { setError('Nhập hạn mức hoàn tiền lớn hơn 0.'); return; } update(s => ({ ...s, cashbackCap: n })); setError(''); notify('Đã lưu cấu hình hoàn tiền mẫu.'); }
  return <Screen title="Ưu đãi & hoàn tiền" back><Card style={{ padding: 12 }}><Row><Icon name="card-outline" /><View style={{ flex: 1 }}><T size={11} color={c.muted}>VPBank StepUp <T size={9} color={c.primary}>Đang cấu hình</T></T><T size={14} bold>Mastercard (•••• 1204)</T></View><Icon name="chevron-down" size={16} /></Row></Card><Card><Row><T size={11} color={c.muted} style={{ flex: 1 }}>HẠN MỨC HOÀN TIỀN THÁNG</T><Pressable accessibilityRole="button" onPress={() => setEditingCap(!editingCap)} style={{ padding: 8 }}><T size={11} color={c.primary}>☷ Chỉnh sửa</T></Pressable></Row><T size={25} bold>640.000 <T size={12} color={c.muted}>/ {money(state.cashbackCap)}</T></T><Row><T size={10} color={c.muted} style={{ flex: 1 }}>Đã tích lũy ước tính ({Math.round(640000 / state.cashbackCap * 100)}%)</T><T size={10} color={c.primary}>Còn {money(Math.max(0, state.cashbackCap - 640000))}</T></Row><Progress value={640000 / state.cashbackCap * 100} color={c.lavender} />{editingCap ? <Field label="Hạn mức hoàn tiền tháng (VND)" value={cap} onChangeText={setCap} keyboardType="numeric" error={error} /> : null}</Card>
    <Section title="Quy tắc danh mục hoàn tiền" />{[{ name: 'Ẩm thực & Nhà hàng', rate: '15%', cap: 300000, icon: 'restaurant-outline' as const, codes: state.mcc }, { name: 'Mua sắm Online & TMĐT', rate: '10%', cap: 300000, icon: 'bag-handle-outline' as const, codes: ['5311', '5999'] }, { name: 'Bảo hiểm & Y tế', rate: '6%', cap: 200000, icon: 'medkit-outline' as const, codes: ['6300', '8099'] }].map(g => <Card key={g.name}><Row><Icon name={g.icon} color={c.lavender} /><View style={{ flex: 1 }}><T bold>{g.name}</T><T size={12} color={c.muted}>Trần {money(g.cap)}/tháng</T></View><Badge>{g.rate}</Badge></Row><T size={10} color={c.muted}>Mã MCC đã gán:</T><Row style={{ flexWrap: 'wrap', gap: 6 }}>{g.codes.map(code => <Badge key={code}>{code}</Badge>)}</Row></Card>)}
    <Card><T size={12} bold>Thêm nhanh mã MCC</T><Field label="Các mã MCC, phân tách bằng dấu phẩy" placeholder="5812, 5814, 5462" value={mcc} onChangeText={setMcc} /><Button label="Thêm mã MCC" kind="secondary" onPress={() => { const codes = mcc.split(',').map(x => x.trim()).filter(Boolean); if (!codes.length || codes.some(x => !/^\d{4}$/.test(x))) { notify('Mỗi MCC phải có đúng 4 chữ số. Có thể thêm nhiều mã bằng dấu phẩy.'); return; } update(s => ({ ...s, mcc: [...new Set([...s.mcc, ...codes])] })); setMcc(''); }} /></Card>
    <Section title="Ưu đãi độc quyền liên kết thẻ" /><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 10 }}>{[['Shopee Mall', 'Hoàn 80.000 đ', 'Đơn từ 400.000 đ vào mỗi Thứ 4 & Chủ Nhật'], ['GrabFood / Car', 'Giảm 25%', 'Tối đa 50.000 đ cho chuyến xe hoặc đặt món'], ['CGV Cinema', 'Mua 1 Tặng 1', 'Vé 2D tiêu chuẩn vào cuối tuần'], ['Starbucks', 'Nâng size miễn phí', 'Áp dụng mọi hóa đơn đồ uống nguyên giá']].map(([name, offer, note], i) => <View key={name} style={{ width: '48%' }}><Card style={{ padding: 12 }}><Row style={{ gap: 6 }}><Image source={[require('../assets/reference/offers-0.png'), require('../assets/reference/offers-1.png'), require('../assets/reference/offers-2.png'), require('../assets/reference/offers-3.png')][i]} style={{ width: 32, height: 32, borderRadius: 16 }} /><View style={{ flex: 1 }}><T size={10} bold>{name}</T><T size={9} color={i > 1 ? c.lavender : c.primary}>{offer}</T></View></Row><T size={9} color={c.muted}>{note}</T></Card></View>)}</View><Button label="Lưu cấu hình quy tắc" kind="secondary" onPress={save} /><Button label="Xem lịch sử cập nhật" kind="secondary" onPress={() => notify('Cấu hình được lưu cục bộ trên thiết bị.')} />{dialog}
  </Screen>;
}
export function CreditStats() {
  const [period, setPeriod] = useState('6T'); const [card, setCard] = useState('all'); const { notify, dialog } = useNotice();
  const debt = card === 'all' ? 42850000 : card === 'platinum' ? 28400000 : card === 'cashback' ? 9800000 : 4650000;
  return <Screen title="Thống kê hạn mức & dư nợ" subtitle="Phân tích sử dụng vốn tín dụng Kira Bank" back>
    <Chips value={card} onChange={setCard} values={[{ value: 'all', label: 'Tất cả các thẻ (3)' }, { value: 'platinum', label: 'Kira Platinum Infinite' }, { value: 'cashback', label: 'Kira Cashback' }, { value: 'virtual', label: 'Cyber Virtual' }]} />
    <Card tint><Row><T bold style={{ flex: 1 }}>Hạn mức & Tỷ lệ sử dụng</T><Badge>Điểm CIC: Tối ưu</Badge></Row><Row><Gauge value={Math.floor(debt / 150000000 * 1000) / 10} /><View style={{ flex: 1, gap: 12 }}><View><T size={11} color={c.muted}>Dư nợ hiện tại (Đã dùng)</T><FitValue size={21} value={money(debt)} /></View><View><T size={11} color={c.muted}>Hạn mức khả dụng còn lại</T><FitValue size={17} color={c.text} value={money(150000000 - debt)} /></View></View></Row><T size={11} color={c.muted}>Tổng hạn mức phê duyệt: 150.000.000 đ</T><Progress value={debt / 150000000 * 100} /><T size={10} color={c.primary}>0 đ                 Khuyên dùng: &lt;30%                 150 Tr</T></Card>
    <Card><T bold>Biến động dư nợ 6 kỳ sao kê</T><T size={11} color={c.muted}>So với trần hạn mức 150M</T><Chips value={period} onChange={setPeriod} values={['3T', '6T', '1N'].map(value => ({ label: value, value }))} /><T size={12} color={c.primary}>Kỳ T10: 42.85M VND   +18% so với T09</T><T size={10} color={c.muted}>Chi tiêu chạm đỉnh đợt Mega Sale 10.10 & Vé máy bay</T><TrendChart period={period} /></Card>
    <Card><T bold>Cơ cấu danh mục chi tiêu</T><T size={11} color={c.muted}>Tháng 10/2024</T><Allocation items={[{ label: 'Mua sắm & Tiêu dùng', percent: 42, value: '18.000.000 đ' }, { label: 'Du lịch & Đặt vé', percent: 28, value: '12.000.000 đ' }, { label: 'Ăn uống & Giải trí', percent: 18, value: '7.700.000 đ' }, { label: 'Dịch vụ & Hóa đơn', percent: 12, value: '5.150.000 đ' }]} /></Card>
    <Card tint><Row><Icon name="calendar-outline" /><T bold style={{ flex: 1 }}>Dự báo chu kỳ sao kê tiếp theo</T><Badge>Chốt sau 2 ngày</Badge></Row><Row><Metric label="Ngày chốt sao kê" value="20/10/2024" /><Metric label="Thanh toán tối thiểu" value="2.142.500 đ" /></Row><T size={11} color={c.muted}>Đến hạn: 05/11/2024 • 5% tổng dư nợ</T><Info>Gợi ý thông minh từ Kira AI: Thanh toán trọn vẹn 42.850.000 đ trước ngày 05/11/2024 để hưởng đặc quyền miễn lãi.</Info></Card>
    <Card><Row><Image source={require('../assets/reference/credit-0.png')} style={{ width: 80, height: 56, borderRadius: 12 }} /><View style={{ flex: 1 }}><Badge>Platinum Extra</Badge><T bold>Kira Lounge Pass</T><T size={10} color={c.muted}>Mở khóa 2 phòng chờ VIP hạng thương gia</T></View></Row><T size={11} color={c.primary}>Chi tiêu thêm 7.15M để kích hoạt kỳ này</T></Card>
    <Section title="Lịch sử biến động hạn mức" />{[['Nâng hạn mức tự động', '15/08/2024 • Điểm tín dụng AAA', '+30.000.000 đ'], ['Cài đặt hạn mức tháng', '01/08/2024 • Người dùng tự điều chỉnh', '60.000.000 đ']].map(([title, date, amount]) => <Card key={title}><Row><Icon name="trending-up" /><View style={{ flex: 1 }}><T size={12} bold>{title}</T><T size={10} color={c.muted}>{date}</T></View><T size={12} color={c.primary}>{amount}</T></Row></Card>)}
    <Button label="Thanh toán dư nợ ngay" icon="wallet-outline" onPress={() => notify('Thanh toán được mô phỏng, không chuyển tiền thật.')} /><Button label="Yêu cầu nâng hạn mức tín dụng" kind="secondary" onPress={() => notify('Đã ghi nhận yêu cầu mẫu.')} /><T size={10} color={c.muted} style={{ textAlign: 'center' }}>Bảo vệ bởi Kira Bank Zero-Liability Protection 256-bit</T>{dialog}
  </Screen>;
}
