import React, { useRef, useState } from 'react';
import { Image, Pressable, View } from 'react-native';
import { router } from 'expo-router';
import { Account, decisionNames, Decision, Draft, jobNames, JobStatus, money, dateLabel, typeNames, validDate } from './data';
import { useDemo } from './store';
import { colors as c } from './theme';
import { Badge, Button, Card, Chips, Dialog, Empty, Field, go, Icon, Info, Metric, Progress, Row, Screen, Section, T, useNotice } from './ui';

export function InvestmentNav({ active }: { active: string }) { return <View style={{ borderBottomWidth: 1, borderColor: c.border, paddingBottom: 8 }}><Chips value={active} values={[{ label: 'Tài khoản', value: 'accounts' }, { label: 'Nhập giao dịch', value: 'import' }, { label: 'Hàng đợi AI', value: 'queue' }]} onChange={v => v === 'accounts' ? router.replace('/investment') : go(v)} /></View>; }
export function Accounts() {
  const { state } = useDemo(); const [query, setQuery] = useState(''); const [status, setStatus] = useState('all');
  const shown = state.accounts.filter(a => (status === 'all' || a.status === status) && `${a.name} ${a.code}`.toLowerCase().includes(query.toLowerCase()));
  return <Screen title="Đầu tư"><InvestmentNav active="accounts" /><Row><View style={{ flex: 1 }}><T size={19} bold>Danh sách tài khoản đầu tư</T><T size={11} color={c.muted}>Quản lý định danh và thông tin xác thực dữ liệu</T></View><Badge>{state.accounts.length} tài khoản</Badge></Row><Row><View style={{ flex: 1 }}><Field label="Tìm tài khoản" value={query} onChangeText={setQuery} placeholder="Tìm theo tên, mã tài khoản…" /></View><Button label="Thêm" icon="add" onPress={() => go('account-add')} /></Row><Chips value={status} onChange={setStatus} values={[{ label: `Tất cả (${state.accounts.length})`, value: 'all' }, { label: 'Hoạt động (2)', value: 'active' }, { label: 'Không hoạt động (1)', value: 'paused' }]} />
    {!shown.length ? <Empty title="Không tìm thấy tài khoản" /> : shown.map(a => <Card key={a.id} style={{ padding: 18, gap: 16 }}><Row><T size={15} bold style={{ flex: 1 }}>{a.id === 'ssi' ? 'Tài khoản ' : a.id === 'vcf' ? 'Quỹ mở ' : 'Global '}{a.name}</T><Badge tone={a.status === 'active' ? 'success' : 'muted'}>{a.status === 'active' ? '• Hoạt động' : '• Không hoạt động'}</Badge></Row><View><Badge>{a.currency}</Badge><T size={10} color={c.muted}>MÃ: {a.code}</T></View><Row><View style={{ flex: 1, gap: 4 }}><T size={9} color={c.muted}>♙ TÊN ĐĂNG NHẬP</T><T size={11}>{a.username}</T><T size={9} color={c.muted}>✉ EMAIL ĐĂNG KÝ</T><T size={10}>{a.email}</T></View><View style={{ flex: 1, gap: 4 }}><T size={9} color={c.muted}>♧ SỐ ĐIỆN THOẠI</T><T size={11}>{a.phone}</T><T size={9} color={c.muted}>▣ NGÀY ĐĂNG KÝ</T><T size={11}>{dateLabel(a.registered)}</T></View></Row><Row style={{ justifyContent: 'flex-end' }}><Pressable accessibilityRole="button" onPress={() => go('account-stats', { id: a.id })} style={{ padding: 8 }}><T size={11} color={c.primary}>Thống kê</T></Pressable><Pressable accessibilityRole="button" onPress={() => go('account-edit', { id: a.id })} style={{ padding: 8 }}><T size={11} color={c.primary}>✎ Chỉnh sửa</T></Pressable></Row></Card>)}<Info>Mỗi tài khoản lưu trữ độc lập thông tin đồng bộ dữ liệu. Không can thiệp số dư trực tiếp.</Info>
  </Screen>;
}

export function AccountForm({ id }: { id?: string }) {
  const { state, saveAccount } = useDemo(); const original = state.accounts.find(a => a.id === id); const editing = !!id;
  const [form, setForm] = useState<Account>(original || { id: 'account-' + Date.now(), code: '', name: '', currency: 'VND', status: 'active', username: '', email: '', phone: '', registered: '2024-10-20' });
  const [error, setError] = useState(''); const { notify, dialog } = useNotice();
  const field = (key: keyof Account, value: string) => setForm(f => ({ ...f, [key]: value }));
  if (editing && !original) return <Screen title="Tài khoản" back><Empty title="Tài khoản không còn tồn tại" /></Screen>;
  function save() {
    if (!form.code.trim() || !form.name.trim() || !form.username.trim() || !form.email.trim() || !form.phone.trim()) { setError('Điền đầy đủ mã, tên tài khoản, tên đăng nhập, email và số điện thoại.'); return; }
    if (state.accounts.some(a => a.id !== form.id && a.code.toLowerCase() === form.code.trim().toLowerCase())) { setError('Mã tài khoản đã tồn tại.'); return; }
    if (form.email && !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(form.email)) { setError('Email không hợp lệ.'); return; }
    if (!validDate(form.registered)) { setError('Ngày đăng ký phải có dạng YYYY-MM-DD.'); return; }
    saveAccount({ ...form, code: form.code.trim(), name: form.name.trim() }); router.back();
  }
  return <Screen title={editing ? 'Chỉnh sửa tài khoản' : 'Thêm tài khoản'} subtitle={editing ? 'TÀI KHOẢN LIÊN KẾT' : 'Tài khoản đầu tư mới'} back footer={<Row><View style={{ flex: 1 }}><Button label="Hủy bỏ" kind="secondary" onPress={() => router.back()} /></View><View style={{ flex: 2 }}><Button label={editing ? 'Lưu thay đổi' : 'Tạo tài khoản'} icon={editing ? 'checkmark-circle-outline' : 'add-circle-outline'} onPress={save} /></View></Row>}>
    {editing ? <Card tint><Badge>◈ CHỨNG KHOÁN SSI</Badge><T size={20} bold>{form.name}</T><T size={11} color={c.muted}>Tài khoản chuyên nghiệp tích hợp dòng giao dịch tốc độ cao Kira</T><Info>Đồng bộ dữ liệu thời gian thực. Nếu có thay đổi tại phiên khác, vui lòng tải lại thông tin mới nhất.</Info></Card> : <Info>Liên kết an toàn đa nền tảng. Thông tin tài khoản giao dịch chứng khoán sẽ được mã hóa chuẩn băng giá Glacier Vault 256-bit.</Info>}{error ? <Info tone="error">{error}</Info> : null}
    <Card><Section title="Thông tin tài khoản" /><Field label="Mã tài khoản *" value={form.code} editable={!editing} maxLength={100} onChangeText={v => field('code', v)} autoCapitalize="characters" placeholder="Ví dụ: SSI-001C-VN" /><Field label="Tên tài khoản *" value={form.name} maxLength={150} onChangeText={v => field('name', v)} placeholder="Ví dụ: Tài khoản SSI Pro Trader" /><T size={12} color={c.muted}>Tiền tệ giao dịch *</T><Chips value={form.currency} values={[{ label: 'VND (Đồng)', value: 'VND' }, { label: 'USD (Đô la)', value: 'USD' }]} onChange={v => editing ? notify('Tiền tệ được giữ nguyên sau khi tạo tài khoản.') : field('currency', v)} />{editing ? <><T size={10} color={c.muted}>Không thể thay đổi tiền tệ sau khi tạo tài khoản.</T><T size={12} color={c.muted}>Trạng thái vận hành</T><Chips value={form.status} values={[{ label: '• Hoạt động', value: 'active' }, { label: '• Tạm dừng', value: 'paused' }, { label: '• Đã đóng', value: 'closed' }]} onChange={v => field('status', v)} /></> : null}</Card>
    <Card><Section title="Thông tin đăng ký & Xác thực" /><Info>Lưu ý: Thông tin dưới đây dùng để định danh tài khoản đầu tư, không phải tài khoản ứng dụng Kira Bank.</Info><Field label="Tên đăng nhập *" value={form.username} onChangeText={v => field('username', v)} autoCapitalize="none" placeholder="Nhập định danh sàn giao dịch" /><Field label="Email đăng ký *" value={form.email} onChangeText={v => field('email', v)} keyboardType="email-address" autoCapitalize="none" placeholder="name@example.com" /><Field label="Số điện thoại *" value={form.phone} onChangeText={v => field('phone', v)} keyboardType="phone-pad" placeholder="09xx xxx xxx" /><Field label="Ngày đăng ký (YYYY-MM-DD) *" value={form.registered} onChangeText={v => field('registered', v)} /><Field label="Mật khẩu tài khoản" value="********" secureTextEntry editable={false} hint="Mật khẩu minh họa; không lưu thông tin xác thực thật." /></Card>{dialog}
  </Screen>;
}

export function DraftCard({ draft, editing = true }: { draft: Draft; editing?: boolean }) {
  const { state, editDraft } = useDemo(); const currency = state.accounts.find(a => a.id === draft.accountId)?.currency; const accent = draft.type === 'bonus' ? c.lavender : c.primary;
  return <Card style={{ borderWidth: editing && draft.conflict ? 1 : 0, borderColor: draft.conflict ? '#806334' : c.border, gap: 18 }}><Row style={{ gap: 6 }}>{editing ? <Pressable accessibilityRole="checkbox" aria-checked={draft.selected} accessibilityState={{ checked: draft.selected }} onPress={() => editDraft(draft.id, { selected: !draft.selected })} style={{ minWidth: 28, minHeight: 36, justifyContent: 'center' }}><Icon name={draft.selected ? 'checkbox' : 'square-outline'} size={18} /></Pressable> : <Badge>#{draft.type === 'bonus' ? '02' : '01'}</Badge>}<T size={13} bold style={{ flex: 1 }}>{editing ? typeNames[draft.type] : draft.type === 'bonus' ? 'Khoản thưởng bổ sung' : 'Bản ghi nạp vốn'}</T>{editing && !draft.saved ? <Pressable accessibilityRole="button" onPress={() => go('draft-edit', { id: draft.id })} style={{ padding: 8 }}><T size={11} color={c.primary}>✎ Chỉnh sửa</T></Pressable> : <View style={{ maxWidth: '45%' }}><Badge tone={draft.conflict ? 'error' : 'primary'}>{draft.conflict ? 'Cần duyệt (Trùng lặp tiềm ẩn)' : 'Đề xuất: Thêm mới'}</Badge></View>}</Row>
    {editing && draft.conflict && !draft.saved ? <Info tone="warning">Cần duyệt (Trùng lặp tiềm ẩn). Có 1 giao dịch cùng số tiền trong ngày.</Info> : null}
    <Row><View style={{ flex: 1 }}><T size={10} color={c.muted}>{editing ? 'SỐ TIỀN' : 'Số tiền nhận diện'}</T><T size={editing ? 21 : 25} color={accent} bold>{draft.type === 'withdraw' ? '−' : '+'}{money(draft.amount, currency)}</T></View>{editing ? <View><T size={9} color={c.muted}>NGÀY GIỜ</T><T size={10}>{dateLabel(draft.date)}</T></View> : null}</Row>
    {!editing ? <Row><Metric label="Loại giao dịch" value={typeNames[draft.type]} color={accent} /><Metric label="Trạng thái" value={draft.status === 'done' ? 'Hoàn thành' : 'Chờ xử lý'} color={c.text} /></Row> : null}
    <View style={!editing ? { backgroundColor: '#0c1321', borderRadius: 22, padding: 12, gap: 10 } : { gap: 6 }}>{!editing ? <Row><T size={11} color={c.muted} style={{ flex: 1 }}>Thời gian GD</T><T size={11}>{dateLabel(draft.date)}</T></Row> : null}<Row><T size={10} color={c.muted} style={{ flex: 1 }}>Mã GD bên ngoài</T><T size={10} color={c.primary}>{draft.externalId || '— (Không có)'}</T></Row>{!editing ? <><T size={11} color={c.muted}>{draft.conflict ? 'Ghi chú lưu ý đối soát' : 'Mô tả trích xuất'}</T>{draft.conflict ? <Info tone="error">Đã có 1 khoản {money(draft.amount)} tương tự trong 48 giờ gần nhất. Đề nghị kiểm tra kỹ mã đối tác trước khi ghi sổ.</Info> : <T size={13}>{draft.description}</T>}</> : null}</View>
    {editing ? <Row><T size={10} color={c.muted} style={{ flex: 1 }}>Đề xuất: <T size={10} color={accent}>{draft.conflict ? 'Cần duyệt' : 'Thêm mới'}</T></T><Pressable accessibilityRole="button" onPress={() => go('decision', { id: draft.id })} style={{ padding: 6 }}><T size={10}>Quyết định: {decisionNames[draft.decision]}⌄</T></Pressable></Row> : null}
  </Card>;
}
export function ImportScreen() {
  const { state, update, confirm } = useDemo(); const [accountId, setAccountId] = useState('ssi'); const [confirmOpen, setConfirmOpen] = useState(false); const { notify, dialog } = useNotice();
  const remaining = state.drafts.filter(d => !d.saved); const actionable = remaining.some(d => d.selected && state.jobs.some(j => j.id === d.source && j.status === 'ready'));
  function addBatch() {
    if (remaining.length) { notify('Hãy xử lý lô hiện tại trước khi tạo lô mới. Các bản ghi chưa xác nhận được giữ nguyên.'); return; }
    const account = state.accounts.find(a => a.id === accountId && a.status === 'active'); if (!account) { notify('Chọn tài khoản đang hoạt động.'); return; }
    const id = 'job-' + Date.now();
    update(s => ({ ...s, jobs: [...s.jobs, { id, name: 'chung_tu_mau.png', size: 'Mẫu có sẵn', status: 'pending', attempts: 0, accountId }], drafts: [...s.drafts, { id: 'draft-' + id, accountId, amount: account.currency === 'USD' ? 100 : 1000000, type: 'deposit', date: '2024-10-20T09:30', externalId: 'DEMO-' + id, description: 'Chứng từ mẫu bổ sung', status: 'done', decision: 'accept', conflict: false, selected: true, saved: false, source: id }] })); go('queue');
  }
  return <Screen title="Nhập giao dịch" back footer={<Row><View style={{ flex: 1 }}><T size={11} bold>Đã chọn: {remaining.filter(d => d.selected).length} bản ghi</T><T size={9} color={c.muted}>Sẵn sàng lưu vào sổ GD</T></View><View style={{ flex: 2 }}><Button label="Xác nhận các mục đã chọn" disabled={!actionable} onPress={() => setConfirmOpen(true)} /></View></Row>}><InvestmentNav active="import" /><Row><Badge>Nhập ảnh</Badge><Pressable onPress={() => go('history')} accessibilityRole="button" style={{ padding: 10 }}><T size={11} color={c.muted}>◷ Lịch sử</T></Pressable></Row><Card><T size={9} color={c.primary}>TÀI KHOẢN NGUỒN *</T><Chips value={accountId} onChange={setAccountId} values={state.accounts.filter(a => a.status === 'active').map(a => ({ label: `${a.name} • ${a.currency}`, value: a.id }))} /><T size={10} color={c.success}>Hoạt động</T></Card>
    <Section title="1. Chọn ảnh giao dịch" /><Info>JPEG, PNG hoặc WebP • Tối đa 10 ảnh mỗi lô • Tổng tối đa 50 MB</Info><Card>{state.jobs.slice(0, 2).map(j => <Pressable key={j.id} accessibilityRole="button" onPress={() => go('source', { id: j.id })}><Row><Icon name="image-outline" /><View style={{ flex: 1 }}><T size={12} bold>{j.name}</T><T size={10} color={c.muted}>{j.size} • <T size={10} color={c.success}>Hợp lệ</T></T></View><Icon name="checkmark-circle-outline" size={15} /></Row></Pressable>)}<Row><View style={{ flex: 1 }}><Button label="Thêm ảnh" kind="secondary" icon="add" onPress={() => notify('Đã chọn hai chứng từ mẫu có sẵn.')} /></View><View style={{ flex: 2 }}><Button label="Tạo lô nhập" icon="cloud-upload-outline" onPress={addBatch} /></View></Row></Card>
    <Section title="2. Trạng thái lô nhập" /><Card><Row><T size={11} style={{ flex: 1 }}>Trạng thái lô:</T><Badge>Sẵn sàng</Badge><T size={10} color={c.muted}>Số lượng bản ghi</T></Row><Info>Ảnh đã được AI trích xuất xong. Bạn có thể kiểm tra và xác nhận bên dưới.</Info><Row style={{ gap: 5 }}>{[{ label: 'Phát hiện', value: state.drafts.length }, { label: 'Cần duyệt', value: remaining.filter(d => d.conflict).length }, { label: 'Thêm mới', value: remaining.filter(d => !d.conflict).length }, { label: 'Cập nhật', value: remaining.filter(d => d.decision === 'merge').length }, { label: 'Lỗi', value: 0 }].map(item => <View key={item.label} style={{ flex: 1, padding: 7, backgroundColor: '#141c2e', borderRadius: 20, alignItems: 'center' }}><T size={8} color={c.muted}>{item.label}</T><T size={15} bold color={c.primary}>{item.value}</T></View>)}</Row></Card>
    <Section title="3. Duyệt và chỉnh sửa" /><T size={11} color={c.muted}>Kiểm tra thông tin trước khi xác nhận. Hệ thống sẽ kiểm tra trùng lặp lần nữa khi lưu.</T>{remaining.length ? remaining.map(d => <DraftCard key={d.id} draft={d} />) : <Empty title="Đã xử lý hết bản ghi" description="Tạo lô mẫu mới hoặc mở lịch sử để xem kết quả." action="Xem lịch sử" onPress={() => go('history')} />}<Dialog visible={confirmOpen} title="Ghi nhận giao dịch mẫu?" message="Các mục hợp lệ sẽ được lưu vào lịch sử. Mục xung đột tiếp tục được giữ để xử lý." onClose={() => setConfirmOpen(false)} onConfirm={() => { setConfirmOpen(false); const result = confirm(); go(result.unresolved ? 'result-partial' : 'result-success'); }} />{dialog}</Screen>;
}

export function Queue() {
  const { state, update } = useDemo(); const [filter, setFilter] = useState('all'); const [ownership, setOwnership] = useState('mine'); const [cancelId, setCancelId] = useState(''); const [working, setWorking] = useState<string[]>([]); const timers = useRef<ReturnType<typeof setTimeout>[]>([]);
  function run(id: string) {
    if (working.includes(id)) return;
    update(s => ({ ...s, jobs: s.jobs.map(j => j.id === id && ['pending', 'failed', 'running'].includes(j.status) ? { ...j, status: 'running', attempts: j.attempts + (j.status === 'running' ? 0 : 1) } : j) }));
    setWorking(w => [...w, id]); timers.current.push(setTimeout(() => { update(s => {
      const job = s.jobs.find(j => j.id === id); if (!job || job.status !== 'running') return s;
      const drafts = s.drafts.some(d => d.source === id) ? s.drafts : [...s.drafts, { id: 'draft-' + id, accountId: job.accountId, type: 'deposit' as const, amount: s.accounts.find(a => a.id === job.accountId)?.currency === 'USD' ? 100 : 1000000, date: '2024-10-20T09:30', externalId: 'DEMO-' + id, description: 'Giao dịch từ chứng từ mẫu', status: 'done' as const, decision: 'accept' as const, conflict: false, selected: true, saved: false, source: id }];
      return { ...s, drafts, jobs: s.jobs.map(j => j.id === id ? { ...j, status: 'ready' as const } : j) };
    }); setWorking(w => w.filter(x => x !== id)); }, 1400));
  }
  const jobs = state.jobs.filter(j => filter === 'all' || j.status === filter);
  const action = (label: string, onPress: () => void, primary = false, disabled = false) => <Pressable key={label} accessibilityRole="button" accessibilityState={{ disabled }} disabled={disabled} onPress={onPress} style={{ flex: 1, minHeight: 36, paddingHorizontal: 8, paddingVertical: 9, backgroundColor: primary ? c.primary : '#1a2639', borderRadius: 24, opacity: disabled ? 0.5 : 1, justifyContent: 'center', alignItems: 'center' }}><T size={10} bold color={primary ? c.ink : c.muted} style={{ textAlign: 'center' }}>{label}</T></Pressable>;
  return <Screen title="Hàng đợi AI" back><InvestmentNav active="queue" /><Row style={{ justifyContent: 'space-between' }}><T size={21} bold>Hàng đợi AI</T><Badge>• Tự cập nhật</Badge></Row><Chips value={ownership} onChange={setOwnership} values={[{ value: 'all-jobs', label: `Tất cả công việc (${state.jobs.length})` }, { value: 'mine', label: `Công việc của tôi (${state.jobs.length})` }]} /><Chips value={filter} onChange={setFilter} values={[{ label: 'Tất cả trạng thái', value: 'all' }, ...Object.entries(jobNames).map(([value, label]) => ({ value, label: `${label} (${state.jobs.filter(j => j.status === value).length})` }))]} />
    {jobs.length ? jobs.map(j => <Card key={j.id} style={{ borderWidth: 1, borderColor: j.status === 'ready' ? '#214b46' : j.status === 'failed' ? '#63343e' : c.border, gap: 16 }}><Row><Icon name={j.status === 'pending' ? 'hourglass-outline' : 'document-text-outline'} color={j.status === 'ready' ? c.success : c.primary} /><View style={{ flex: 1 }}><T size={12} bold>{j.name}</T><T size={10} color={c.muted}>#{j.id} • {j.size}</T></View><View style={{ maxWidth: '36%' }}><Badge tone={j.status === 'failed' ? 'error' : j.status === 'ready' || j.status === 'confirmed' ? 'success' : 'primary'}>{jobNames[j.status].toUpperCase()}</Badge></View></Row><Row><View style={{ flex: 1 }}><T size={10} color={c.muted}>Số lần chạy</T><T size={12}>{j.attempts} / 3</T></View><View style={{ alignItems: 'flex-end' }}><T size={10} color={c.muted}>Thời gian tạo</T><T size={11}>18/10/2024 14:20:10</T></View></Row>
    {j.status === 'running' ? <><Progress value={working.includes(j.id) ? 65 : 30} /><T size={11} color={c.primary}>⟳ Đang trích xuất dữ liệu và chuẩn hóa…</T></> : null}{j.status === 'ready' ? <Row><T size={10} color={c.muted} style={{ flex: 1 }}>Thời gian hoàn tất</T><T size={10} color={c.success}>18/10/2024 14:21:05</T></Row> : null}{j.status === 'failed' ? <Info tone="error">Ảnh bị mờ hoặc không nhận diện được hóa đơn hợp lệ.</Info> : null}
    <Row style={{ gap: 6 }}>{action('Xem ảnh', () => go('source', { id: j.id }))}{j.status === 'ready' ? <>{action('Kết quả AI', () => go('ai-result', { id: j.id }))}{action('Duyệt & Xác nhận →', () => go('import'), true)}</> : j.status === 'confirmed' ? action('Xem lịch sử', () => go('history')) : j.status === 'cancelled' ? null : action(j.status === 'failed' ? 'Thử lại' : j.status === 'running' ? 'Hoàn tất xử lý' : 'Chạy công việc', () => run(j.id), false, working.includes(j.id))}</Row>{j.status === 'pending' ? <Pressable accessibilityRole="button" accessibilityLabel="Hủy công việc" onPress={() => setCancelId(j.id)} style={{ alignSelf: 'flex-end', padding: 8 }}><T size={11} color={c.error}>⊗ Hủy công việc</T></Pressable> : null}</Card>) : <Empty title="Không có công việc phù hợp" />}
    <Info>Cơ chế xử lý ảnh độc lập. AI xử lý bất đồng bộ theo từng ảnh độc lập. Bạn có thể rời màn hình và quay lại sau mà không làm gián đoạn tiến trình.</Info><Dialog visible={!!cancelId} title="Hủy công việc đang chờ?" message="Chứng từ mẫu sẽ giữ trạng thái đã hủy." onClose={() => setCancelId('')} onConfirm={() => { update(s => s.jobs.some(j => j.id === cancelId && j.status === 'pending') ? ({ ...s, drafts: s.drafts.filter(d => d.source !== cancelId || d.saved), jobs: s.jobs.map(j => j.id === cancelId ? { ...j, status: 'cancelled' } : j) }) : s); setCancelId(''); }} /></Screen>;
}

export function SourceImage({ id }: { id: string }) {
  const { state } = useDemo(); const [zoom, setZoom] = useState(1); const job = state.jobs.find(j => j.id === id);
  return <Screen title={job?.name || 'Ảnh nguồn chứng từ'} subtitle="#JOB-98214 • Glacier Vault Verified • AI Ready" back><Badge>• 4K HIGH-RES SOURCE</Badge><View style={{ minHeight: 300, justifyContent: 'center', overflow: 'hidden' }}><Image source={id === 'job-1' ? require('../assets/reference/source-0.png') : state.accounts.find(a => a.id === job?.accountId)?.currency === 'USD' ? require('../assets/receipt-usd.png') : require('../assets/receipt-vnd.png')} resizeMode="contain" style={{ width: '100%', height: 280 * zoom, borderRadius: 16 }} /></View><Row><T size={11} color={c.muted} style={{ flex: 1 }}>⌕ {Math.round(zoom * 100)}%</T><Pressable accessibilityRole="button" accessibilityLabel="Thu nhỏ" onPress={() => setZoom(v => Math.max(0.5, v - 0.25))} style={{ padding: 12 }}><Icon name="remove" size={18} /></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Vừa khung" onPress={() => setZoom(1)} style={{ padding: 12 }}><T size={11}>Fit</T></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Phóng to" onPress={() => setZoom(v => Math.min(3, v + 0.25))} style={{ padding: 12 }}><Icon name="add" size={18} /></Pressable></Row><Card><Row><Icon name="document-lock-outline" /><View style={{ flex: 1 }}><T bold>Thông số chứng từ</T><T size={10} color={c.muted}>Khối dữ liệu tự động đồng bộ</T></View><Badge>Khả dụng</Badge></Row><Row><Metric label="ĐỊNH DẠNG & KÍCH THƯỚC" value={`PNG • ${job?.size || '2.4 MB'}`} /><Metric label="THỜI GIAN TẢI LÊN" value="14:20:10" /></Row><T size={10} color={c.muted}>2400 × 1800 px (300 DPI) • 18/10/2024 (GMT+7)</T><Info>Glacier Vault Encrypted Storage • SHA-256 • Mã hóa tệp</Info><Info>Đã trích xuất sẵn 4 trường giao dịch. AI Vision Kira đã đối soát số tiền khớp với danh mục nhập tiền đầu tư từ dòng Quỹ Alpha.</Info><Row><View style={{ flex: 1 }}><Button label="Đóng" kind="secondary" onPress={() => router.back()} /></View><View style={{ flex: 2 }}><Button label="Kết quả AI chuẩn hóa" disabled={!job || !['ready', 'confirmed'].includes(job.status)} onPress={() => go('ai-result', { id })} /></View></Row></Card></Screen>;
}
export function AiResult({ id }: { id: string }) {
  const { state } = useDemo(); const [mode, setMode] = useState('visual'); const job = state.jobs.find(j => j.id === id); const drafts = state.drafts.filter(d => d.source === id);
  return <Screen title="Kết quả AI chuẩn hóa" back><T size={12} color={c.muted}>{job?.name || 'Không tìm thấy công việc'}</T>{job && ['ready', 'confirmed'].includes(job.status) ? <><Chips value={mode} onChange={setMode} values={[{ label: 'Bản trực quan dễ đọc', value: 'visual' }, { label: 'Mã JSON chuẩn hóa', value: 'json' }]} /><Card><Row><Icon name="scan-outline" size={30} /><View style={{ flex: 1 }}><T size={13} color={c.primary} bold>TÓM TẮT TIẾN TRÌNH</T><T size={15} bold>Trích xuất thành công {drafts.length} giao dịch độc lập từ 1 ảnh chứng từ.</T><T size={11} color={c.muted}>{drafts.length} bản ghi riêng biệt • Cấu trúc hoàn chỉnh</T></View><Badge>Sẵn sàng</Badge></Row></Card>{mode === 'visual' ? drafts.map(d => <DraftCard key={d.id} draft={d} editing={false} />) : <Card><T size={12}>{JSON.stringify(drafts.map(d => ({ type: d.type, amount: d.amount, date: d.date, externalId: d.externalId, description: d.description })), null, 2)}</T></Card>}<Button label="Xem ảnh gốc" kind="secondary" onPress={() => go('source', { id })} /><Button label="Chuyển đến duyệt & xác nhận" onPress={() => go('import')} /></> : <Empty title="Kết quả chưa sẵn sàng" action="Mở hàng đợi" onPress={() => go('queue')} />}</Screen>;
}
export function DraftEdit({ id }: { id: string }) {
  const { state, editDraft } = useDemo(); const original = state.drafts.find(d => d.id === id); const [form, setForm] = useState(original); const [amount, setAmount] = useState(String(original?.amount || '')); const [error, setError] = useState('');
  if (!form || !original || original.saved) return <Screen title="Chỉnh sửa bản ghi" back><Empty title="Bản ghi đã xử lý hoặc không tồn tại" /></Screen>;
  function save() { const n = Number(amount); if (!Number.isFinite(n) || n <= 0) { setError('Số tiền phải lớn hơn 0.'); return; } if (!validDate(form!.date, true)) { setError('Thời gian phải có dạng YYYY-MM-DDTHH:mm.'); return; } editDraft(id, { ...form!, amount: n, decision: original!.decision }); router.back(); }
  return <Screen title="Chỉnh sửa bản ghi giao dịch" back sheet footer={<Button label="Áp dụng chỉnh sửa" onPress={save} />}><Badge>BẢN NHÁP · CHƯA GHI SỔ</Badge>{original.conflict ? <Info tone="warning">Giao dịch có khả năng trùng. Chọn cách xử lý phù hợp trước khi xác nhận.</Info> : null}{error ? <Info tone="error">{error}</Info> : null}<Field label="Ngày giờ giao dịch" value={form.date} onChangeText={date => setForm({ ...form, date })} hint="YYYY-MM-DDTHH:mm" /><Chips value={form.type} values={Object.entries(typeNames).map(([value, label]) => ({ value, label }))} onChange={type => setForm({ ...form, type: type as Draft['type'] })} /><Field label="Số tiền" keyboardType="numeric" value={amount} onChangeText={setAmount} /><Chips value={form.status} values={[{ label: 'Hoàn thành', value: 'done' }, { label: 'Chờ xử lý', value: 'pending' }]} onChange={status => setForm({ ...form, status: status as Draft['status'] })} /><Field label="Mã giao dịch bên ngoài" value={form.externalId} onChangeText={externalId => setForm({ ...form, externalId })} /><Field label="Mô tả" value={form.description} multiline maxLength={1000} onChangeText={description => setForm({ ...form, description })} /><Card><T bold>Cách xử lý đang chọn</T><T color={c.primary}>{decisionNames[original.decision]}</T><Button label="Thay đổi cách xử lý" kind="secondary" onPress={() => go('decision', { id })} /></Card><Info>Áp dụng chỉ cập nhật bản nháp, chưa ghi giao dịch vào lịch sử.</Info></Screen>;
}
export function DecisionScreen({ id }: { id: string }) {
  const { state, editDraft } = useDemo(); const draft = state.drafts.find(d => d.id === id); const [decision, setDecision] = useState<Decision>(draft?.decision || 'accept');
  const notes: Record<Decision, string> = { accept: 'Lưu bản ghi nếu không còn phát hiện xung đột.', merge: 'Giữ giao dịch hiện có, bổ sung mô tả và trạng thái. Không cộng tiền lần nữa.', new: 'Chọn khi đây thực sự là một giao dịch khác. Mã giao dịch bên ngoài vẫn phải không trùng.', skip: 'Không ghi bản ghi này vào lịch sử.' };
  return <Screen title="Cách xử lý giao dịch" back sheet footer={<Button label="Áp dụng cách xử lý" disabled={!draft || draft.saved} onPress={() => { editDraft(id, { decision }); router.back(); }} />}><T size={12} color={c.muted}>Chọn phương án xử lý cho bản ghi giao dịch #02</T><T color={c.muted}>{draft ? money(draft.amount) : 'Không tìm thấy bản ghi'}</T>{(Object.keys(decisionNames) as Decision[]).map(key => <Pressable key={key} accessibilityRole="radio" aria-checked={key === decision} accessibilityState={{ selected: key === decision }} onPress={() => setDecision(key)}><Card style={{ borderWidth: key === decision ? 1 : 0, borderColor: key === decision ? '#335872' : c.border, backgroundColor: key === decision ? '#0e3044' : c.surface }}><Row><Icon name={key === decision ? 'radio-button-on' : 'radio-button-off'} /><T bold style={{ flex: 1 }}>{decisionNames[key]}</T></Row><T size={13} color={c.muted}>{notes[key]}</T></Card></Pressable>)}<Info>Quyết định có hiệu lực khi bạn xác nhận tại màn duyệt.</Info></Screen>;
}
export function ConfirmationResult({ partial }: { partial: boolean }) {
  const { state } = useDemo(); const r = state.result;
  return <Screen title="Kết quả xác nhận" subtitle="#BATCH-202410-889 • SSI Pro Trader (VND)" back>
    <Card tint style={{ alignItems: partial ? 'flex-start' : 'center', paddingVertical: 24 }}><Icon name={partial ? 'warning-outline' : 'checkmark-circle'} size={partial ? 32 : 58} color={partial ? c.error : c.primary} /><Badge tone={partial ? 'error' : 'primary'}>{partial ? 'YÊU CẦU CAN THIỆP' : 'Mục 5.4 • Hoàn tất 100%'}</Badge><T size={20} bold style={{ textAlign: partial ? 'left' : 'center' }}>{partial ? 'Xác nhận thành công một phần' : 'Xác nhận thành công toàn bộ'}</T><T size={12} color={c.muted} style={{ textAlign: partial ? 'left' : 'center' }}>{partial ? 'Một số bản ghi đã được ghi nhận, tuy nhiên vẫn còn bản ghi phát sinh xung đột hoặc cần xử lý thêm trước khi hoàn tất.' : 'Tất cả các bản ghi đã được ghi nhận vào sổ giao dịch độc lập của tài khoản đầu tư.'}</T></Card>
    <Section title="Chỉ số đối soát sau xác nhận" /><Row><Metric label="Thêm mới" value={String(r.added).padStart(2, '0')} /><Metric label="Cập nhật" value={String(r.updated).padStart(2, '0')} /></Row><Row><Metric label="Bỏ qua" value={String(r.skipped).padStart(2, '0')} /><Metric label={partial ? 'Cần xử lý / Lỗi' : 'Lỗi ghi nhận'} value={String(r.unresolved).padStart(2, '0')} color={r.unresolved ? c.error : c.primary} /></Row>
    {partial ? <Info>Bản ghi lỗi vẫn được giữ lại trong lô để bạn tiếp tục điều chỉnh cách xử lý. Các bản ghi hợp lệ đã được chuyển vào lịch sử giao dịch.</Info> : null}<Section title={partial ? 'Chi tiết kết quả theo bản ghi' : 'Danh sách bản ghi tóm tắt'} />
    {state.drafts.map((d, i) => <Card key={d.id} style={{ gap: 10 }}><Row><Badge>#{String(i + 1).padStart(2, '0')}</Badge><T size={13} bold style={{ flex: 1 }}>{typeNames[d.type]}</T><Badge tone={!d.saved ? 'error' : d.decision === 'skip' ? 'muted' : 'primary'}>{!d.saved ? 'Lỗi xác nhận' : d.decision === 'skip' ? 'Đã bỏ qua' : 'Đã ghi nhận mới'}</Badge></Row><Row><T size={10} color={c.muted} style={{ flex: 1 }}>{dateLabel(d.date)}</T><T size={15} bold color={d.type === 'bonus' ? c.lavender : c.primary}>{d.type === 'withdraw' ? '−' : '+'}{money(d.amount)}</T></Row>{!d.saved ? <><Info tone="error">Phát hiện xung đột tiềm tàng trong 48h chưa được chỉ định phương án.</Info><Pressable accessibilityRole="button" onPress={() => go('draft-edit', { id: d.id })} style={{ padding: 8 }}><T size={11} color={c.primary}>Khắc phục xung đột ›</T></Pressable></> : <T size={10} color={c.muted}>{d.decision === 'skip' ? 'Giao dịch bị bỏ qua theo yêu cầu người dùng.' : `Trạng thái giao dịch gốc • ${d.status === 'done' ? 'Hoàn thành' : 'Chờ xử lý'}`}</T>}</Card>)}
    {!partial ? <Info>Dữ liệu giao dịch đầu tư được lưu độc lập để theo dõi và đối soát, không làm thay đổi số dư thực tế hoặc số dư tại tài khoản.</Info> : null}{partial ? <Button label={`Tiếp tục xử lý bản ghi còn lại (${r.unresolved})`} onPress={() => go('import')} /> : null}<Button label="Xem lịch sử giao dịch" kind={partial ? 'secondary' : 'primary'} icon="time-outline" onPress={() => go('history')} /><Row><View style={{ flex: 1 }}><Button label="Tạo lô nhập mới" kind="secondary" onPress={() => go('import')} /></View><View style={{ flex: 1 }}><Button label="Về Đầu tư" kind="secondary" onPress={() => router.replace('/investment')} /></View></Row>
  </Screen>;
}
