import React, { useState } from 'react';
import { Image, Pressable, Switch, View } from 'react-native';
import { router } from 'expo-router';
import { useDemo } from './store';
import { colors as c } from './theme';
import { Badge, Button, Card, Dialog, go, Icon, Info, Row, Screen, Section, T, useNotice } from './ui';
export function DemoTools() {
  const { state, scenario } = useDemo(); const [pending, setPending] = useState(''); const [notifications, setNotifications] = useState(true); const { notify, dialog } = useNotice();
  const scenarios = [
    { name: 'reference-history', label: 'Mockup · Lịch sử & chi tiết', description: 'Năm giao dịch và ba hồ sơ tra soát đúng mẫu.', target: 'history' },
    { name: 'reference-account', label: 'Mockup · Thống kê tài khoản', description: 'Kịch bản thống kê 180 triệu, độc lập với số dư demo mặc định.', target: 'account-stats' },
    { name: 'reference-partial', label: 'Mockup · Kết quả một phần', description: 'Một thêm mới, một bỏ qua, một cần xử lý.', target: 'result-partial' },
    { name: 'reference-success', label: 'Mockup · Kết quả toàn bộ', description: 'Hai bản ghi đã ghi nhận.', target: 'result-success' },
    { name: 'reference-filter', label: 'Mockup · Bộ lọc', description: 'SSI, nạp và thưởng, kỳ tháng 10/2024.', target: 'filter' },
    { name: 'ready', label: 'Mặc định · Xung đột một phần', description: 'Một giao dịch hợp lệ, một khoản thưởng cần đối chiếu.', target: 'import' },
    { name: 'success', label: 'Xác nhận thành công toàn bộ', description: 'Hai bản ghi hợp lệ, không có xung đột.', target: 'import' },
    { name: 'empty', label: 'Lịch sử trống', description: 'Thử màn trống trước khi nhập giao dịch.', target: 'history' },
    { name: 'pending', label: 'AI đang chờ', description: 'Thử chạy hoặc hủy công việc.', target: 'queue' },
    { name: 'running', label: 'AI đang xử lý', description: 'Thử trạng thái tải và mô phỏng hoàn tất.', target: 'queue' },
    { name: 'failed', label: 'AI thất bại', description: 'Thử thông báo lỗi và thao tác thử lại.', target: 'queue' },
  ];
  return <Screen title="Cá nhân"><Card tint style={{ alignItems: 'center', paddingVertical: 28 }}><View style={{ width: 76, height: 76, borderRadius: 38, backgroundColor: '#25425a', alignItems: 'center', justifyContent: 'center' }}><T size={26} bold color={c.primary}>MT</T></View><T size={24} bold>Nguyễn Minh Triết</T><T color={c.muted}>triet@example.com</T><Badge>HỒ SƠ MINH HỌA</Badge></Card><Section title="Tùy chọn ứng dụng" /><Card><Row><Icon name="language-outline" /><View style={{ flex: 1 }}><T bold>Ngôn ngữ</T><T size={12} color={c.muted}>Tiếng Việt</T></View></Row><Row><Icon name="notifications-outline" /><View style={{ flex: 1 }}><T bold>Thông báo mẫu</T><T size={12} color={c.muted}>Chỉ thay đổi công tắc giao diện</T></View><Switch accessibilityLabel="Thông báo mẫu" value={notifications} onValueChange={setNotifications} trackColor={{ false: c.elevated, true: '#235979' }} thumbColor={notifications ? c.primary : c.muted} /></Row><Button label="Bảo mật & quyền thiết bị" kind="secondary" onPress={() => notify('Bản demo không kích hoạt Face ID, không yêu cầu camera hoặc kết nối tài khoản thật.')} /><Button label="Kết nối đối tác" kind="secondary" onPress={() => notify('Kết nối và đồng bộ đối tác nằm ngoài bản demo.')} /></Card><Section title="Khám phá các kịch bản" /><Info>Chọn kịch bản sẽ thay thế dữ liệu demo hiện tại. Các thay đổi chỉ lưu trên thiết bị này.</Info>{scenarios.map(item => <Card key={item.name}><Row><T bold style={{ flex: 1 }}>{item.label}</T>{state.scenario === item.name ? <Badge>Đang chọn</Badge> : null}</Row><T size={12} color={c.muted}>{item.description}</T><Button label="Mở kịch bản" kind="secondary" onPress={() => setPending(item.name)} /></Card>)}<Button label="Đặt lại dữ liệu mẫu" kind="danger" onPress={() => setPending('reset')} /><Button label="Đăng xuất" kind="secondary" onPress={() => notify('Bạn đang dùng hồ sơ demo, không có phiên đăng nhập thật để đăng xuất.')} /><T size={11} color={c.muted} style={{ textAlign: 'center' }}>KIRA LIFE MOBILE · GLACIER · V1 DEMO</T><Dialog visible={!!pending} title="Thay thế dữ liệu demo?" message="Các tài khoản, bản nháp và báo cáo bạn đã thay đổi trong demo sẽ được đặt lại." confirmLabel="Đặt lại và tiếp tục" onClose={() => setPending('')} onConfirm={() => { const selected = scenarios.find(s => s.name === pending); scenario(pending === 'reset' ? 'ready' : pending); setPending(''); if (selected) go(selected.target, selected.target === 'account-stats' ? { id: 'ssi' } : {}); else router.replace('/'); }} />{dialog}</Screen>;
}

export function Profile() {
  const [biometric, setBiometric] = useState(true); const { notify, dialog } = useNotice();
  const setting = (icon: React.ComponentProps<typeof Icon>['name'], title: string, detail: string, accessory?: React.ReactNode) => <Pressable accessibilityRole="button" accessibilityLabel={title} onPress={() => notify(`${title}: chức năng đang được mô phỏng trên thiết bị.`)} style={{ flexDirection: 'row', alignItems: 'center', gap: 12, minHeight: 72 }}><View style={{ width: 42, height: 42, borderRadius: 22, backgroundColor: '#1c3041', alignItems: 'center', justifyContent: 'center' }}><Icon name={icon} /></View><View style={{ flex: 1 }}><T size={15} bold>{title}</T><T size={11} color={c.muted} style={{ marginTop: 2 }} >{detail}</T></View>{accessory || <Icon name="chevron-forward" size={16} color={c.muted} />}</Pressable>;
  return <Screen title="Cá nhân">
    <Card tint style={{ padding: 22, gap: 22 }}><Row><Image source={require('../assets/reference/profile-0.png')} style={{ width: 66, height: 66, borderRadius: 33, borderWidth: 2, borderColor: c.primary }} /><View style={{ flex: 1, gap: 4 }}><T size={21} bold>Nguyễn Minh Triết</T><T size={12} color={c.muted}>triet.nguyen@kirabank.vn</T><Badge>◈ Priority Banking</Badge><T size={10} color={c.muted}>#KIRA-889210</T></View></Row><Card style={{ padding: 12 }}><Row><Icon name="finger-print" /><View style={{ flex: 1 }}><T size={12} bold>CCCD gắn chip • Chuẩn sinh trắc học</T><T size={10} color={c.muted}>Bảo vệ định danh bởi Trung tâm Dữ liệu Quốc gia</T></View><Icon name="checkmark-circle-outline" size={18} /></Row></Card></Card>
    <Section title="Cấu hình bảo mật & nền tảng" /><Card>{setting('id-card-outline', 'Xác thực sinh trắc học', 'FaceID & Cảm biến vân tay siêu âm', <Switch accessibilityLabel="Xác thực sinh trắc học" value={biometric} onValueChange={setBiometric} trackColor={{ false: c.elevated, true: c.primary }} thumbColor={c.surface} />)}{setting('timer-outline', 'Khóa khi vào nền', 'Tự động khóa sau thời gian chờ', <Badge>1 phút</Badge>)}{setting('phone-portrait-outline', 'Thiết bị đã cấp quyền', 'iPhone 15 Pro Max (Thiết bị này), iPad Pro')}</Card>
    <Section title="Tích hợp hệ thống & đồng bộ" /><Card>{setting('qr-code-outline', 'Liên kết Open Banking / VietQR', 'Tự động nhận diện chuỗi giao dịch liên kết', <Badge>Kích hoạt</Badge>)}{setting('analytics-outline', 'Danh mục đầu tư liên kết', 'SSI Chứng khoán, VNDirect, VinaCapital')}{setting('camera-outline', 'Quyền thiết bị (Camera & Ảnh)', 'Quét OCR hóa đơn, chuyển khoản & eKYC')}</Card>
    <Section title="Tùy chọn ứng dụng" /><Card>{setting('globe-outline', 'Ngôn ngữ hiển thị', 'Giao diện ngôn ngữ chính', <T size={12}>Tiếng Việt</T>)}{setting('notifications-outline', 'Thông báo & Báo động thẻ', 'Biến động số dư tức thời & Hạn thanh toán tín dụng')}{setting('headset-outline', 'Hướng dẫn & Trợ giúp kỹ thuật', 'Tổng đài viên Priority 24/7 & Tra cứu nghiệp vụ')}</Card>
    <Button label="Đăng xuất tài khoản & Xóa phiên làm việc" kind="danger" icon="log-out-outline" onPress={() => notify('Đây là hồ sơ mô phỏng, không có phiên đăng nhập thật.')} /><T size={10} color={c.muted} style={{ textAlign: 'center' }}>• Kira Bank Mobile v2.4.0 (Build 20241018)</T><T size={9} color="#4a6070" style={{ textAlign: 'center', letterSpacing: 1 }}>GLACIER ENGINE • END-TO-END CRYPTOGRAPHY ACTIVE</T>{dialog}
  </Screen>;
}
