application:
  datasource:
    write:
      jdbc-url: "jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:kira-dev}?useUnicode=true&createDatabaseIfNotExist=true"
      username: "${DB_USERNAME:root}"
      password: "${DB_PASSWORD:1234}"
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 5
spring:
  application:
    name: kira-queue
  profiles:
    active: composite
  output:
    ansi:
      enabled: NEVER
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  task:
    scheduling:
      pool:
        size: 12
    execution:
      pool:
        core-size: 12
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    virtual-host: ${nesdpetn:/}
    connection-timeout: 60000      # 60s
    requested-heartbeat: 30        # heartbeat 30s
    listener:
      simple:
        acknowledge-mode: auto        # ack tự động sau khi xử lý thành công
        concurrency: 1                # số consumer thread khởi tạo
        max-concurrency: 1           # scale tối đa 1 thread khi backlog tăng
        prefetch: 1                   # mỗi consumer lấy 1 message -> xử lý xong mới lấy tiếp
        retry:
          enabled: true
          max-attempts: 5             # thử lại tối đa 5 lần nếu consumer ném exception
          initial-interval: 5000ms    # lần retry đầu cách 5s
          multiplier: 2.0             # exponential backoff (5s, 10s, 20s…)
          max-interval: 60000ms       # tối đa delay giữa các lần retry = 60s
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: false
server:
  port: 2323
  servlet:
    context-path: /queue
  compression:
    enabled: true
    min-response-size: 512

logging:
  level:
    root: info
  file:
    name: target/queue.log
